
import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'EN' | 'PT' | 'FR' | 'DE' | 'LB';

export const LANGUAGES_LIST = [
  { code: 'FR', label: 'Français', flag: '🇫🇷' },
  { code: 'EN', label: 'English', flag: '🇬🇧' },
  { code: 'PT', label: 'Português', flag: '🇧🇷' },
  { code: 'DE', label: 'Deutsch', flag: '🇩🇪' },
  { code: 'LB', label: 'Lëtzebuergesch', flag: '🇱🇺' },
];

const TRANSLATIONS = {
  EN: {
    // ... existing ...
    acceptAndChat: "Accept & Open Chat",
    // Company Creation Flow
    noCompany: "Don't have a company yet?",
    openCompanyBtn: "Open Company with ServiceBid",
    formationTitle: "Company Formation Service",
    formationSubtitle: "We handle the administrative procedures to set up your legal status in Luxembourg, so you can focus on working.",
    formStep1: "Project Details",
    formStep2: "Documents",
    businessType: "Target Structure",
    independantType: "Indépendant (Sole Proprietorship)",
    sarlsType: "SARL-S (Simplified Company)",
    activityDesc: "Description of Activity",
    activityPlace: "Ex: Painting, renovation, electrical consulting...",
    residency: "Current Residency",
    residencyLux: "I live in Luxembourg",
    residencyEU: "I live in the EU",
    residencyNonEU: "Non-EU Resident",
    docPassport: "Passport / ID Card",
    docCriminal: "Criminal Record (Casier Judiciaire)",
    submitRequest: "Submit Formation Request",
    requestSent: "Request Sent Successfully!",
    requestSentDesc: "Our legal team will review your details and contact you within 24 hours to proceed with the establishment authorization.",
    backToHome: "Back to Home",
    // Auth & Generic
    welcomeTitle: "Welcome to ServiceBid",
    welcomeSubtitle: "The transparent marketplace for trusted services.",
    imClient: "I'm a Client",
    imClientDesc: "I need a service done.",
    imPro: "I'm a Professional",
    imProDesc: "I want to offer my services.",
    heroTitle: "The service you need, <span class='text-emerald-500'>the way you want.</span>",
    heroSubtitle: "Receive up to 4 quotes from rated professionals in minutes.",
    searchPlaceholder: "Ex: Mechanic, Electrician, Solar...",
    popularCategories: "Popular Categories",
    proCTA: "Are you a professional?",
    proCTADesc: "Increase your revenue by serving clients near you.",
    proCTABtn: "Register my business",
    trustSecure: "Secure",
    trustStars: "4.9/5 Stars",
    trustFast: "Fast",
    // Navigation
    myRequests: "My Requests",
    manageRequests: "Manage your requests and quotes",
    openRequests: "Open Requests",
    historyTab: "History",
    messagesTab: "Messages",
    noRequests: "No active requests.",
    noRequestsDesc: "Your completed services will appear here.",
    statusWaiting: "Status: Waiting for Quotes",
    received: "Received",
    budgetForYou: "Quotes for you",
    viewDetails: "View Details",
    hireNow: "Hire Now",
    loggedAs: "Logged in as",
    profile: "My Profile",
    dashboard: "Dashboard",
    logout: "Logout",
    stepXofY: "Step {x} of {y}",
    back: "Back",
    next: "Next",
    finish: "Submit Registration",
    saveChanges: "Save Changes",
    // Wizard
    whatNeed: "What do you need?",
    describeProblem: "Describe your problem",
    whereWhen: "Where and when?",
    defineLocation: "Define location and urgency",
    photosOptional: "Photos & Budget",
    helpPro: "Set your budget and add photos",
    titleLabel: "Request Title",
    titlePlaceholder: "Ex: Repair shower wiring",
    detailsLabel: "Details",
    detailsPlaceholder: "Describe what happened, brands, models...",
    addressPlaceholder: "Your address or ZIP code",
    whenLabel: "When?",
    urgencyAsap: "ASAP",
    urgencyThisWeek: "This week",
    urgencyPlanning: "Just researching",
    addPhoto: "Add",
    photoTip: "Photos help professionals provide more accurate quotes and avoid surprises.",
    requestQuotes: "Request Quotes",
    budgetLabel: "Your Budget Estimate",
    budgetPlaceholder: "0",
    budgetHelp: "Enter the amount you are willing to pay for this service.",
    // Profile
    personalInfo: "Personal Info",
    addressLogistics: "Address & Logistics",
    security: "Security",
    manageIdentity: "Manage your identity and communication languages.",
    smartAddress: "Smart address engine based on Luxembourg registry.",
    logisticsNote: "Logistics Note",
    luxNoteDesc: "In Luxembourg, specifying elevator and parking helps providers organize better.",
    languages: "Languages",
    personalDetails: "Identity & Residence",
    businessDetails: "Legal Structure",
    licenseDetails: "Business License",
    bankDetails: "Bank Details",
    reviewDetails: "Review & Sign",
    fullName: "Full Name",
    cnsNumber: "Social Security (CNS) - 13 digits",
    address: "Address",
    street: "Street",
    houseNumber: "Number",
    postalCode: "Postal Code (L-XXXX)",
    locality: "Locality",
    idUpload: "ID Card / Residence Permit",
    legalType: "Legal Entity Type",
    independant: "Independent",
    societe: "Company (SARL/SA)",
    rcsNumber: "RCS Number",
    tvaNumber: "VAT Number (LU + 8 digits)",
    companyName: "Company Name",
    licenseUpload: "Establishment Authorization",
    licenseNum: "License Number",
    licenseExpiry: "Validity Date",
    iban: "IBAN (SEPA)",
    accHolder: "Account Holder",
    declaration: "I declare that the information is true and I am authorized to work in the Grand Duchy.",
    memberSince: "Member since",
    rating: "Rating",
    jobs: "Jobs",
    xp: "XP",
    // Categories
    Cleaning: "Cleaning",
    Electrician: "Electrician",
    Plumbing: "Plumbing",
    Gardening: "Gardening",
    "IT Support": "IT Support",
    Moving: "Moving",
    Beauty: "Beauty",
    "Pet Sitter": "Pet Sitter",
    Mechanic: "Mechanic (Car/Bike)",
    ElectricVehicle: "Electric Car Specialist",
    AutoBody: "Auto Body & Paint",
    Micromobility: "Scooters & E-Bikes",
    SolarEnergy: "Solar & Batteries",
    // Pro Dashboard
    nearby: "Nearby Requests",
    yourOffer: "Your Offer",
    sendBid: "Send Bid",
    radar: "Radar Active",
    // Login
    login: "Login",
    email: "Email Address",
    password: "Password",
    phoneLabel: "Phone Number",
    forgotPassword: "Forgot password?",
    dontHaveAccount: "Don't have an account?",
    signUp: "Sign Up",
    loginWithPhone: "Phone",
    loginWithEmail: "Email",
    signIn: "Sign In",
    demoClient: "Client Demo",
    demoPro: "Professional Demo",
    // Instagram & Portfolio
    connectPortfolio: "Connect your Portfolio",
    connectPortfolioDesc: "Automatically showcase your best work. We sync photos and videos from your Instagram Professional account.",
    connectBtn: "Connect Instagram",
    connecting: "Connecting...",
    autoSync: "Auto-syncs every 24h",
    instaConnected: "Instagram Connected",
    itemsSynced: "items synced",
    disconnect: "Disconnect",
    noCaption: "No caption provided.",
    postedOn: "Posted on",
    wantService: "I want this service",
    instaPortfolio: "Instagram Portfolio",
    viewInstaBtn: "View Portfolio on Instagram (Reels & Photos)",
    bio: "Bio",
    serviceTimeline: "Service Timeline",
    // Client Dashboard
    liveMarket: "Live Market",
    monitoringBids: "Monitoring professional bids",
    targetBudget: "Target Budget",
    averageOffer: "Average Offer",
    incomingOffers: "Incoming Offers",
    realTime: "Real-time",
    viewPhotos: "View Photos 📸",
    viewFullProfile: "View Full Profile & Reviews",
    budgetFit: "Budget Fit",
    aboveTarget: "Above Target",
    acceptOffer: "Accept Offer",
    // Requests & Actions
    actions: "Actions",
    editRequest: "Edit Request",
    deleteRequest: "Delete",
    pauseMonitoring: "Pause Monitoring",
    resumeMonitoring: "Resume Monitoring",
    goToMarket: "Go to Live Market",
    monitoringPaused: "Monitoring Paused",
    monitoringActive: "Active Monitoring",
    noActiveRequests: "No active requests found.",
    createFirstRequest: "Create your first request",
    selectRequestToView: "Select a request to view the Live Market",
    // Chat
    serviceAgreed: "Service agreed for",
    chatStarted: "Chat started.",
    serviceCompleted: "Service Completed!",
    experienceQuestion: "How was your experience with",
    writeReview: "Write a short review...",
    submitReview: "Submit Review",
    onlineNow: "Online now",
    finishJob: "Finish Job",
    typeMessage: "Type a message...",
    // Landing
    exploreServices: "Explore services near you",
    results: "results",
    noServices: "No services found for",
    clearSearch: "Clear search",
    offerLabel: "Offer",
    // --- NEW: Analytics, Workflow & Guard ---
    financialPerformance: "Financial Performance",
    totalEarnings: "Total Earnings",
    jobsCompleted: "Jobs Completed",
    breakdown: "Breakdown",
    noJobsPeriod: "No jobs found for this period.",
    filterToday: "TODAY",
    filterWeek: "WEEK",
    filterMonth: "MONTH",
    filterYear: "YEAR",
    // Service Status
    statusConfirmed: "Service Confirmed",
    subConfirmed: "Waiting for professional to start route.",
    statusEnRoute: "On the Way",
    subEnRoute: "Professional is driving to your location.",
    statusArrived: "Arrived",
    subArrived: "Professional is at the location.",
    statusInProgress: "In Progress",
    subInProgress: "Service is being performed.",
    statusCompleted: "Completed",
    subCompleted: "Service finished. Check receipt below.",
    recording: "Recording",
    // Pro Actions
    actionOnWay: "I'm on my way",
    actionArrived: "I've Arrived",
    actionStart: "Start Service",
    actionFinish: "Finish Service",
    // System Messages
    msgOnWay: "🚗 The professional is on the way.",
    msgArrived: "📍 The professional has arrived at the location.",
    msgStarted: "⏱️ Service started.",
    msgPriceUpdate: "System: The service price was updated to €",
    // Receipt
    receiptTitle: "Service Receipt",
    startTime: "Start Time",
    endTime: "End Time",
    duration: "Duration",
    total: "Total",
    // Navigation Guard
    leaveNegotiation: "Leave Negotiation?",
    leaveNegotiationDesc: "Do you want to return to the Live Market? This chat will be saved in your Messages tab, and you can see new offers from other professionals.",
    returnToMarket: "Return to Market",
    stayHere: "Stay Here",
    // Offer Modals
    updateOffer: "Update Offer",
    newPrice: "New Price (€)",
    reasonChange: "Reason for change",
    sendUpdate: "Send Update",
    confirmChange: "Confirm Change?",
    confirmChangeDesc: "The service price will be updated to",
    confirmChangeSuffix: "The difference will be charged to your main payment method.",
    yesConfirm: "Yes, Confirm Update",
    cancel: "Cancel",
    proposalUpdate: "Proposal Update",
    offerAccepted: "Offer Accepted",
    offerDeclined: "Offer Declined"
  },
  FR: {
    // ... existing ...
    acceptAndChat: "Accepter & Ouvrir Chat",
    noCompany: "Pas encore d'entreprise ?",
    openCompanyBtn: "Ouvrir avec ServiceBid",
    formationTitle: "Service de Création d'Entreprise",
    formationSubtitle: "Nous gérons les démarches administratives pour établir votre statut légal au Luxembourg, afin que vous puissiez vous concentrer sur votre travail.",
    formStep1: "Détails du Projet",
    formStep2: "Documents",
    businessType: "Structure Cible",
    independantType: "Indépendant (Entreprise Individuelle)",
    sarlsType: "SARL-S (Simplifiée)",
    activityDesc: "Description de l'Activité",
    activityPlace: "Ex: Peinture, rénovation, conseil électrique...",
    residency: "Résidence Actuelle",
    residencyLux: "J'habite au Luxembourg",
    residencyEU: "J'habite en UE",
    residencyNonEU: "Résident Hors UE",
    docPassport: "Passeport / Carte d'Identité",
    docCriminal: "Casier Judiciaire",
    submitRequest: "Envoyer la Demande",
    requestSent: "Demande Envoyée !",
    requestSentDesc: "Notre équipe juridique examinera vos détails et vous contactera sous 24h pour procéder à l'autorisation d'établissement.",
    backToHome: "Retour à l'accueil",
    welcomeTitle: "Bienvenue sur ServiceBid",
    welcomeSubtitle: "Le marché transparent pour des services de confiance.",
    imClient: "Je suis Client",
    imClientDesc: "J'ai besoin d'un service.",
    imPro: "Je suis Professionnel",
    imProDesc: "Je veux offrir mes services.",
    heroTitle: "Le service qu'il vous faut, <span class='text-emerald-500'>comme vous le voulez.</span>",
    heroSubtitle: "Recevez jusqu'à 4 devis de professionnels évalués en quelques minutes.",
    searchPlaceholder: "Ex: Mécanique, Électricien, Solaire...",
    popularCategories: "Catégories Populaires",
    proCTA: "Vous êtes professionnel ?",
    proCTADesc: "Augmentez votre chiffre d'affaires en servant des clients près de chez vous.",
    proCTABtn: "Enregistrer mon entreprise",
    trustSecure: "Sécurisé",
    trustStars: "4.9/5 Étoiles",
    trustFast: "Rapide",
    myRequests: "Mes Demandes",
    manageRequests: "Gerez vos demandes et devis",
    openRequests: "Demandes Ouvertes",
    historyTab: "Historique",
    messagesTab: "Messages",
    noRequests: "Aucune demande active.",
    noRequestsDesc: "Vos services terminés apparaîtront ici.",
    statusWaiting: "Status: En attente de devis",
    received: "Reçus",
    budgetForYou: "Devis pour vous",
    viewDetails: "Voir Détails",
    hireNow: "Engager Maintenant",
    loggedAs: "Connecté en tant que",
    profile: "Mon Profil",
    dashboard: "Tableau de Bord",
    logout: "Déconnexion",
    stepXofY: "Étape {x} sur {y}",
    back: "Retour",
    next: "Suivant",
    finish: "Soumettre l'Inscription",
    saveChanges: "Enregistrer",
    whatNeed: "De quoi avez-vous besoin ?",
    describeProblem: "Décrivez votre problème",
    whereWhen: "Où et quand ?",
    defineLocation: "Définissez le lieu et l'urgence",
    photosOptional: "Photos & Budget",
    helpPro: "Définissez votre budget et ajoutez des photos",
    titleLabel: "Titre de la demande",
    titlePlaceholder: "Ex: Réparer câblage douche",
    detailsLabel: "Détails",
    detailsPlaceholder: "Décrivez ce qui s'est passé, marques, modèles...",
    addressPlaceholder: "Votre adresse ou Code Postal",
    whenLabel: "Pour quand ?",
    urgencyAsap: "Dès que possible",
    urgencyThisWeek: "Cette semaine",
    urgencyPlanning: "En recherche",
    addPhoto: "Ajouter",
    photoTip: "Les photos aident les pros à donner des devis précis et évitent les surprises.",
    requestQuotes: "Demander des Devis",
    budgetLabel: "Votre Estimation du Budget",
    budgetPlaceholder: "0",
    budgetHelp: "Entrez le montant que vous êtes prêt à payer pour ce service.",
    personalInfo: "Infos Personnelles",
    addressLogistics: "Adresse & Logistique",
    security: "Sécurité",
    manageIdentity: "Gerez votre identité et vos langues de communication.",
    smartAddress: "Moteur d'adresse intelligent basé sur le registre du Luxembourg.",
    logisticsNote: "Note Logistique",
    luxNoteDesc: "Au Luxembourg, préciser l'ascenseur et le parking aide les prestataires à s'organiser.",
    languages: "Langues",
    personalDetails: "Identité et Résidence",
    businessDetails: "Structure Légale",
    licenseDetails: "Autorisation d'Établissement",
    bankDetails: "Coordonnées Bancaires",
    reviewDetails: "Révision et Contrat",
    fullName: "Nom Complet",
    cnsNumber: "N° Matricule (CNS) - 13 chiffres",
    address: "Adresse",
    street: "Rue",
    houseNumber: "Numéro",
    postalCode: "Code Postal (L-XXXX)",
    locality: "Localité",
    idUpload: "Carte d'Identité / Titre de Séjour",
    legalType: "Type d'Entité",
    independant: "Indépendant",
    societe: "Société (SARL/SA)",
    rcsNumber: "N° RCS",
    tvaNumber: "N° de TVA (LU + 8 chiffres)",
    companyName: "Nom de la Société",
    licenseUpload: "Autorisation d'Établissement",
    licenseNum: "N° d'Autorisation",
    licenseExpiry: "Date d'Expiration",
    iban: "IBAN (SEPA)",
    accHolder: "Titulaire du Compte",
    declaration: "Je déclare que les informations sont vraies et que je suis autorisé à travailler au Grand-Duché.",
    Cleaning: "Nettoyage",
    Electrician: "Électricien",
    Plumbing: "Plomberie",
    Gardening: "Jardinage",
    "IT Support": "Support IT",
    Moving: "Déménagement",
    Beauty: "Beauté",
    "Pet Sitter": "Garde d'animaux",
    Mechanic: "Mécanicien (Auto/Moto)",
    ElectricVehicle: "Spécialiste Véhicule Électrique",
    AutoBody: "Carrosserie et Peinture",
    Micromobility: "Trottinettes et E-Bikes",
    SolarEnergy: "Solaire et Batteries",
    memberSince: "Membre depuis",
    rating: "Évaluation",
    jobs: "Jobs",
    xp: "XP",
    nearby: "Demandes à Proximité",
    yourOffer: "Votre Offre",
    sendBid: "Envoyer l'Offre",
    radar: "Radar Actif",
    login: "Connexion",
    email: "E-mail",
    password: "Mot de passe",
    phoneLabel: "Téléphone",
    forgotPassword: "Mot de passe oublié?",
    dontHaveAccount: "Pas encore de compte?",
    signUp: "S'inscrire",
    loginWithPhone: "Téléphone",
    loginWithEmail: "E-mail",
    signIn: "Se Connecter",
    demoClient: "Démo Client",
    demoPro: "Démo Professionnel",
    // Instagram & Portfolio
    connectPortfolio: "Connectez votre Portfolio",
    connectPortfolioDesc: "Montrez automatiquement votre meilleur travail. Nous synchronisons photos et vidéos depuis votre compte Instagram Professionnel.",
    connectBtn: "Connecter Instagram",
    connecting: "Connexion...",
    autoSync: "Synchro auto toutes les 24h",
    instaConnected: "Instagram Connecté",
    itemsSynced: "éléments synchronisés",
    disconnect: "Déconnecter",
    noCaption: "Aucune légende fournie.",
    postedOn: "Publié le",
    wantService: "Je veux ce service",
    instaPortfolio: "Portfolio Instagram",
    viewInstaBtn: "Voir le Portfolio sur Instagram (Reels & Photos)",
    bio: "Biographie",
    serviceTimeline: "Historique des Services",
    // Client Dashboard
    liveMarket: "Marché en Direct",
    monitoringBids: "Suivi des offres professionnelles",
    targetBudget: "Budget Cible",
    averageOffer: "Offre Moyenne",
    incomingOffers: "Offres Entrantes",
    realTime: "Temps réel",
    viewPhotos: "Voir Photos 📸",
    viewFullProfile: "Voir Profil Complet & Avis",
    budgetFit: "Dans le Budget",
    aboveTarget: "Au-dessus du Budget",
    acceptOffer: "Accepter l'Offre",
    // Requests & Actions
    actions: "Actions",
    editRequest: "Modifier la demande",
    deleteRequest: "Supprimer",
    pauseMonitoring: "Suspendre le suivi",
    resumeMonitoring: "Reprendre le suivi",
    goToMarket: "Voir le Marché",
    monitoringPaused: "Suivi Suspendu",
    monitoringActive: "Suivi Actif",
    noActiveRequests: "Aucune demande active trouvée.",
    createFirstRequest: "Créez votre première demande",
    selectRequestToView: "Sélectionnez une demande pour voir le Marché en Direct",
    // Chat
    serviceAgreed: "Service convenu pour",
    chatStarted: "Discussion commencée.",
    serviceCompleted: "Service Terminé !",
    experienceQuestion: "Comment s'est passée votre expérience avec",
    writeReview: "Écrivez un court avis...",
    submitReview: "Soumettre l'Avis",
    onlineNow: "En ligne",
    finishJob: "Terminer le Job",
    typeMessage: "Écrivez un message...",
    // Landing
    exploreServices: "Explorez les services près de chez vous",
    results: "résultats",
    noServices: "Aucun service trouvé pour",
    clearSearch: "Effacer la recherche",
    offerLabel: "Offre",
    // --- NEW: Analytics, Workflow & Guard ---
    financialPerformance: "Performance Financière",
    totalEarnings: "Gains Totaux",
    jobsCompleted: "Jobs Terminés",
    breakdown: "Détails",
    noJobsPeriod: "Aucun job trouvé pour cette période.",
    filterToday: "AUJ.",
    filterWeek: "SEM.",
    filterMonth: "MOIS",
    filterYear: "ANNÉE",
    // Service Status
    statusConfirmed: "Service Confirmé",
    subConfirmed: "En attente du départ du professionnel.",
    statusEnRoute: "En Route",
    subEnRoute: "Le professionnel conduit vers vous.",
    statusArrived: "Arrivé",
    subArrived: "Le professionnel est sur place.",
    statusInProgress: "En Cours",
    subInProgress: "Le service est en cours d'exécution.",
    statusCompleted: "Terminé",
    subCompleted: "Service terminé. Voir le reçu ci-dessous.",
    recording: "Enregistrement",
    // Pro Actions
    actionOnWay: "Je suis en route",
    actionArrived: "Je suis arrivé",
    actionStart: "Commencer le Service",
    actionFinish: "Terminer le Service",
    // System Messages
    msgOnWay: "🚗 Le professionnel est en route.",
    msgArrived: "📍 Le professionnel est arrivé sur place.",
    msgStarted: "⏱️ Service commencé.",
    msgPriceUpdate: "Système : Le prix du service a été mis à jour à €",
    // Receipt
    receiptTitle: "Reçu de Service",
    startTime: "Heure Début",
    endTime: "Heure Fin",
    duration: "Durée",
    total: "Total",
    // Navigation Guard
    leaveNegotiation: "Quitter la Négociation ?",
    leaveNegotiationDesc: "Voulez-vous retourner au Marché en Direct ? Ce chat sera sauvegardé dans l'onglet Messages, et vous pourrez voir de nouvelles offres.",
    returnToMarket: "Retourner au Marché",
    stayHere: "Rester Ici",
    // Offer Modals
    updateOffer: "Mettre à jour l'Offre",
    newPrice: "Nouveau Prix (€)",
    reasonChange: "Raison du changement",
    sendUpdate: "Envoyer Mise à Jour",
    confirmChange: "Confirmer le Changement ?",
    confirmChangeDesc: "Le prix du service sera mis à jour à",
    confirmChangeSuffix: "La différence sera débitée de votre méthode de paiement principale.",
    yesConfirm: "Oui, Confirmer",
    cancel: "Annuler",
    proposalUpdate: "Mise à Jour Proposition",
    offerAccepted: "Offre Acceptée",
    offerDeclined: "Offre Refusée"
  },
  PT: {
    // ... existing ...
    acceptAndChat: "Aceitar e Ir para o Chat",
    noCompany: "Ainda não tem empresa?",
    openCompanyBtn: "Abrir Empresa com ServiceBid",
    formationTitle: "Serviço de Abertura de Empresa",
    formationSubtitle: "Cuidamos dos trâmites administrativos para estabelecer seu status legal no Luxemburgo, para que você foque no trabalho.",
    formStep1: "Detalhes do Projeto",
    formStep2: "Documentos",
    businessType: "Estrutura Alvo",
    independantType: "Independente (Empresa Individual)",
    sarlsType: "SARL-S (Simplificada)",
    activityDesc: "Descrição da Atividade",
    activityPlace: "Ex: Pintura, reformas, consultoria elétrica...",
    residency: "Residência Atual",
    residencyLux: "Moro no Luxemburgo",
    residencyEU: "Moro na UE",
    residencyNonEU: "Residente fora da UE",
    docPassport: "Passaporte / Cartão de Cidadão",
    docCriminal: "Registo Criminal (Casier Judiciaire)",
    submitRequest: "Enviar Pedido de Abertura",
    requestSent: "Pedido Enviado com Sucesso!",
    requestSentDesc: "Nossa equipe jurídica analisará seus detalhes e entrará em contato em 24h para prosseguir com a autorização de estabelecimento.",
    backToHome: "Voltar ao Início",
    welcomeTitle: "Bem-vindo ao ServiceBid",
    welcomeSubtitle: "O mercado transparente para serviços de confiança.",
    imClient: "Sou Cliente",
    imClientDesc: "Preciso de um serviço.",
    imPro: "Sou Profissional",
    imProDesc: "Quero oferecer serviços.",
    heroTitle: "O serviço que você precisa, <span class='text-emerald-500'>do jeito que você quer.</span>",
    heroSubtitle: "Receba até 4 orçamentos de profissionais avaliados em minutos.",
    searchPlaceholder: "Ex: Mecânico, Eletricista, Solar...",
    popularCategories: "Categorias Populares",
    proCTA: "Você é profissional?",
    proCTADesc: "Aumente seu faturamento atendendo clientes próximos a você.",
    proCTABtn: "Cadastrar meu negócio",
    trustSecure: "Seguro",
    trustStars: "4.9/5 Estrelas",
    trustFast: "Rápido",
    myRequests: "Meus Pedidos",
    manageRequests: "Gerencie suas solicitações e orçamentos",
    openRequests: "Pedidos em Aberto",
    historyTab: "Histórico",
    messagesTab: "Mensagens",
    noRequests: "Nenhum pedido ativo.",
    noRequestsDesc: "Seus serviços concluídos aparecerão aqui.",
    statusWaiting: "Status: Aguardando Orçamentos",
    received: "Recebidos",
    budgetForYou: "Orçamentos para você",
    viewDetails: "Ver Detalhes",
    hireNow: "Contratar Agora",
    loggedAs: "Logado como",
    profile: "Meu Perfil",
    dashboard: "Painel",
    logout: "Sair",
    stepXofY: "Passo {x} de {y}",
    back: "Voltar",
    next: "Próximo",
    finish: "Enviar Cadastro",
    saveChanges: "Guardar Alterações",
    whatNeed: "O que você precisa?",
    describeProblem: "Descreva seu problema",
    whereWhen: "Onde e quando?",
    defineLocation: "Defina local e urgência",
    photosOptional: "Fotos e Orçamento",
    helpPro: "Defina seu orçamento e adicione fotos",
    titleLabel: "Título do Pedido",
    titlePlaceholder: "Ex: Consertar fiação chuveiro",
    detailsLabel: "Detalhes",
    detailsPlaceholder: "Descreva o que aconteceu, marcas, modelos...",
    addressPlaceholder: "Seu endereço ou CEP",
    whenLabel: "Para quando?",
    urgencyAsap: "O quanto antes",
    urgencyThisWeek: "Nesta semana",
    urgencyPlanning: "Estou pesquisando",
    addPhoto: "Adicionar",
    photoTip: "Fotos ajudam profissionais a darem orçamentos mais precisos e evita surpresas.",
    requestQuotes: "Solicitar Orçamentos",
    budgetLabel: "Sua Estimativa de Orçamento",
    budgetPlaceholder: "0",
    budgetHelp: "Insira o valor que você está disposto a pagar por este serviço.",
    personalInfo: "Dados Pessoais",
    addressLogistics: "Endereço e Logística",
    security: "Segurança",
    manageIdentity: "Gerencie sua identidade e idiomas de comunicação.",
    smartAddress: "Motor de endereço inteligente baseado no registo do Luxemburgo.",
    logisticsNote: "Nota Logística",
    luxNoteDesc: "No Luxemburgo, especificar elevador e estacionamento ajuda os prestadores a organizarem-se melhor.",
    languages: "Idiomas",
    personalDetails: "Identidade e Residência",
    businessDetails: "Estrutura Legal",
    licenseDetails: "Licença Comercial",
    bankDetails: "Dados Bancários",
    reviewDetails: "Revisão e Contrato",
    fullName: "Nome Completo",
    cnsNumber: "N° de Matrícula (CNS) - 13 dígitos",
    address: "Endereço",
    street: "Rua",
    houseNumber: "Número",
    postalCode: "Código Postal (L-XXXX)",
    locality: "Localidade",
    idUpload: "Bilhete de Identidade / Título de Residência",
    legalType: "Tipo de Entidade",
    independant: "Independente",
    societe: "Sociedade (SARL/SA)",
    rcsNumber: "Número RCS",
    tvaNumber: "Número de IVA (LU + 8 dígitos)",
    companyName: "Nome da Empresa",
    licenseUpload: "Autorização de Estabelecimento",
    licenseNum: "Número da Licença",
    licenseExpiry: "Data de Validade",
    iban: "IBAN (SEPA)",
    accHolder: "Titular da Conta",
    declaration: "Declaro que as informações são verdadeiras e possuo autorização para trabalhar no Grão-Ducado.",
    Cleaning: "Limpeza",
    Electrician: "Eletricista",
    Plumbing: "Encanador",
    Gardening: "Jardinagem",
    "IT Support": "Suporte TI",
    Moving: "Mudanças",
    Beauty: "Estética",
    "Pet Sitter": "Pet Sitter",
    Mechanic: "Mecânico (Carro/Mota)",
    ElectricVehicle: "Especialista Carro Elétrico",
    AutoBody: "Pintura e Chaparia",
    Micromobility: "Trotinetes e E-Bikes",
    SolarEnergy: "Energia Solar e Baterias",
    memberSince: "Membro desde",
    rating: "Avaliação",
    jobs: "Trabalhos",
    xp: "XP",
    nearby: "Pedidos Próximos",
    yourOffer: "Sua Oferta",
    sendBid: "Enviar Lance",
    radar: "Radar Ativo",
    login: "Entrar",
    email: "E-mail",
    password: "Senha",
    phoneLabel: "Celular",
    forgotPassword: "Esqueceu a senha?",
    dontHaveAccount: "Não tem uma conta?",
    signUp: "Cadastre-se",
    loginWithPhone: "Celular",
    loginWithEmail: "E-mail",
    signIn: "Acessar Conta",
    demoClient: "Demo Cliente",
    demoPro: "Demo Profissional",
    // Instagram & Portfolio
    connectPortfolio: "Conecte seu Portfólio",
    connectPortfolioDesc: "Mostre seu melhor trabalho automaticamente. Sincronizamos fotos e vídeos da sua conta Instagram Profissional.",
    connectBtn: "Conectar Instagram",
    connecting: "Conectando...",
    autoSync: "Auto-sync a cada 24h",
    instaConnected: "Instagram Conectado",
    itemsSynced: "itens sincronizados",
    disconnect: "Desconectar",
    noCaption: "Sem legenda.",
    postedOn: "Postado em",
    wantService: "Quero este serviço",
    instaPortfolio: "Portfólio do Instagram",
    viewInstaBtn: "Ver Portfólio no Instagram (Reels & Fotos)",
    bio: "Bio",
    serviceTimeline: "Histórico de Serviços",
    // Client Dashboard
    liveMarket: "Mercado ao Vivo",
    monitoringBids: "Monitorando ofertas profissionais",
    targetBudget: "Orçamento Alvo",
    averageOffer: "Oferta Média",
    incomingOffers: "Ofertas Recebidas",
    realTime: "Tempo Real",
    viewPhotos: "Ver Fotos 📸",
    viewFullProfile: "Ver Perfil Completo e Avaliações",
    budgetFit: "No Orçamento",
    aboveTarget: "Acima do Alvo",
    acceptOffer: "Aceitar Oferta",
    // Requests & Actions
    actions: "Ações",
    editRequest: "Editar Pedido",
    deleteRequest: "Excluir",
    pauseMonitoring: "Pausar Monitoramento",
    resumeMonitoring: "Retomar Monitoramento",
    goToMarket: "Ir para Mercado ao Vivo",
    monitoringPaused: "Monitoramento Pausado",
    monitoringActive: "Monitoramento Ativo",
    noActiveRequests: "Nenhum pedido ativo encontrado.",
    createFirstRequest: "Crie seu primeiro pedido",
    selectRequestToView: "Selecione um pedido para ver o Mercado ao Vivo",
    // Chat
    serviceAgreed: "Serviço acordado por",
    chatStarted: "Chat iniciado.",
    serviceCompleted: "Serviço Concluído!",
    experienceQuestion: "Como foi sua experiência com",
    writeReview: "Escreva uma avaliação curta...",
    submitReview: "Enviar Avaliação",
    onlineNow: "Online agora",
    finishJob: "Finalizar Job",
    typeMessage: "Digite uma mensagem...",
    // Landing
    exploreServices: "Explore serviços perto de você",
    results: "resultados",
    noServices: "Nenhum serviço encontrado para",
    clearSearch: "Limpar busca",
    offerLabel: "Oferta",
    // --- NEW: Analytics, Workflow & Guard ---
    financialPerformance: "Desempenho Financeiro",
    totalEarnings: "Ganhos Totais",
    jobsCompleted: "Trabalhos Concluídos",
    breakdown: "Detalhamento",
    noJobsPeriod: "Nenhum trabalho neste período.",
    filterToday: "HOJE",
    filterWeek: "SEM.",
    filterMonth: "MÊS",
    filterYear: "ANO",
    // Service Status
    statusConfirmed: "Serviço Confirmado",
    subConfirmed: "Aguardando profissional iniciar rota.",
    statusEnRoute: "A Caminho",
    subEnRoute: "O profissional está dirigindo até você.",
    statusArrived: "Chegou",
    subArrived: "O profissional está no local.",
    statusInProgress: "Em Andamento",
    subInProgress: "O serviço está sendo executado.",
    statusCompleted: "Concluído",
    subCompleted: "Serviço finalizado. Veja o recibo abaixo.",
    recording: "Gravando",
    // Pro Actions
    actionOnWay: "Estou a caminho",
    actionArrived: "Cheguei ao local",
    actionStart: "Iniciar Serviço",
    actionFinish: "Finalizar Serviço",
    // System Messages
    msgOnWay: "🚗 O profissional está a caminho.",
    msgArrived: "📍 O profissional chegou ao local.",
    msgStarted: "⏱️ Serviço iniciado.",
    msgPriceUpdate: "Sistema: O preço do serviço foi atualizado para €",
    // Receipt
    receiptTitle: "Recibo de Serviço",
    startTime: "Início",
    endTime: "Fim",
    duration: "Duração",
    total: "Total",
    // Navigation Guard
    leaveNegotiation: "Sair da Negociação?",
    leaveNegotiationDesc: "Deseja voltar ao Mercado ao Vivo? Este chat será salvo na aba Mensagens e você poderá ver novas ofertas.",
    returnToMarket: "Voltar ao Mercado",
    stayHere: "Ficar Aqui",
    // Offer Modals
    updateOffer: "Atualizar Oferta",
    newPrice: "Novo Preço (€)",
    reasonChange: "Motivo da alteração",
    sendUpdate: "Enviar Atualização",
    confirmChange: "Confirmar Mudança?",
    confirmChangeDesc: "O preço do serviço será atualizado para",
    confirmChangeSuffix: "A diferença será cobrada no seu método de pagamento principal.",
    yesConfirm: "Sim, Confirmar",
    cancel: "Cancelar",
    proposalUpdate: "Atualização de Proposta",
    offerAccepted: "Oferta Aceita",
    offerDeclined: "Oferta Recusada"
  },
  DE: {
    // ... existing ...
    acceptAndChat: "Akzeptieren & Chat Öffnen",
    noCompany: "Noch keine Firma?",
    openCompanyBtn: "Firma eröffnen mit ServiceBid",
    formationTitle: "Firmengründungsservice",
    formationSubtitle: "Wir kümmern uns um die administrativen Schritte, um Ihren Rechtsstatus in Luxemburg zu etablieren, damit Sie sich auf Ihre Arbeit konzentrieren können.",
    formStep1: "Projektdetails",
    formStep2: "Dokumente",
    businessType: "Zielstruktur",
    independantType: "Selbstständig (Einzelunternehmen)",
    sarlsType: "SARL-S (Vereinfacht)",
    activityDesc: "Beschreibung der Tätigkeit",
    activityPlace: "Bsp: Malerei, Renovatioun, Elektrotechnik...",
    residency: "Aktueller Wohnsitz",
    residencyLux: "Ich wohne in Luxemburg",
    residencyEU: "Ich wohne in der EU",
    residencyNonEU: "Nicht-EU-Bürger",
    docPassport: "Reisepass / Personalausweis",
    docCriminal: "Strafregisterauszug (Casier Judiciaire)",
    submitRequest: "Gründungsantrag Senden",
    requestSent: "Anfrage Erfolgreich Gesendet!",
    requestSentDesc: "Unser Rechtsteam wird Ihre Angaben prüfen und Sie innerhalb von 24 Stunden kontaktieren.",
    backToHome: "Zurück zur Startseite",
    welcomeTitle: "Welcome to ServiceBid",
    welcomeSubtitle: "The transparent marketplace for trusted services.",
    imClient: "I'm a Client",
    imClientDesc: "I need a service done.",
    imPro: "I'm a Professional",
    imProDesc: "I want to offer my services.",
    heroTitle: "The service you need, <span class='text-emerald-500'>the way you want.</span>",
    heroSubtitle: "Receive up to 4 quotes from rated professionals in minutes.",
    searchPlaceholder: "Ex: Mechanic, Electrician, Solar...",
    popularCategories: "Popular Categories",
    proCTA: "Are you a professional?",
    proCTADesc: "Increase your revenue by serving clients near you.",
    proCTABtn: "Register my business",
    trustSecure: "Secure",
    trustStars: "4.9/5 Stars",
    trustFast: "Fast",
    // Navigation
    myRequests: "My Requests",
    manageRequests: "Manage your requests and quotes",
    openRequests: "Open Requests",
    historyTab: "History",
    messagesTab: "Nachrichten",
    noRequests: "No active requests.",
    noRequestsDesc: "Your completed services will appear here.",
    statusWaiting: "Status: Waiting for Quotes",
    received: "Received",
    budgetForYou: "Quotes for you",
    viewDetails: "View Details",
    hireNow: "Hire Now",
    loggedAs: "Logged in as",
    profile: "My Profile",
    dashboard: "Dashboard",
    logout: "Logout",
    stepXofY: "Step {x} of {y}",
    back: "Back",
    next: "Next",
    finish: "Submit Registration",
    saveChanges: "Save Changes",
    // Wizard
    whatNeed: "What do you need?",
    describeProblem: "Describe your problem",
    whereWhen: "Where and when?",
    defineLocation: "Define location and urgency",
    photosOptional: "Photos & Budget",
    helpPro: "Set your budget and add photos",
    titleLabel: "Request Title",
    titlePlaceholder: "Ex: Repair shower wiring",
    detailsLabel: "Details",
    detailsPlaceholder: "Describe what happened, brands, models...",
    addressPlaceholder: "Your address or ZIP code",
    whenLabel: "When?",
    urgencyAsap: "ASAP",
    urgencyThisWeek: "This week",
    urgencyPlanning: "Just researching",
    addPhoto: "Add",
    photoTip: "Photos help professionals provide more accurate quotes and avoid surprises.",
    requestQuotes: "Request Quotes",
    budgetLabel: "Your Budget Estimate",
    budgetPlaceholder: "0",
    budgetHelp: "Enter the amount you are willing to pay for this service.",
    // Profile
    personalInfo: "Personal Info",
    addressLogistics: "Address & Logistics",
    security: "Security",
    manageIdentity: "Manage your identity and communication languages.",
    smartAddress: "Smart address engine based on Luxembourg registry.",
    logisticsNote: "Logistics Note",
    luxNoteDesc: "In Luxembourg, specifying elevator and parking helps providers organize better.",
    languages: "Languages",
    personalDetails: "Identity & Residence",
    businessDetails: "Legal Structure",
    licenseDetails: "Business License",
    bankDetails: "Bank Details",
    reviewDetails: "Review & Sign",
    fullName: "Full Name",
    cnsNumber: "Social Security (CNS) - 13 digits",
    address: "Address",
    street: "Street",
    houseNumber: "Number",
    postalCode: "Postal Code (L-XXXX)",
    locality: "Locality",
    idUpload: "ID Card / Residence Permit",
    legalType: "Legal Entity Type",
    independant: "Independent",
    societe: "Company (SARL/SA)",
    rcsNumber: "RCS Number",
    tvaNumber: "VAT Number (LU + 8 digits)",
    companyName: "Company Name",
    licenseUpload: "Establishment Authorization",
    licenseNum: "License Number",
    licenseExpiry: "Validity Date",
    iban: "IBAN (SEPA)",
    accHolder: "Account Holder",
    declaration: "I declare that the information is true and I am authorized to work in the Grand Duchy.",
    memberSince: "Member since",
    rating: "Rating",
    jobs: "Jobs",
    xp: "XP",
    // Categories
    Cleaning: "Cleaning",
    Electrician: "Electrician",
    Plumbing: "Plumbing",
    Gardening: "Gardening",
    "IT Support": "IT Support",
    Moving: "Moving",
    Beauty: "Beauty",
    "Pet Sitter": "Pet Sitter",
    Mechanic: "Mechanic (Car/Bike)",
    ElectricVehicle: "Electric Car Specialist",
    AutoBody: "Auto Body & Paint",
    Micromobility: "Scooters & E-Bikes",
    SolarEnergy: "Solar & Batteries",
    // Pro Dashboard
    nearby: "Nearby Requests",
    yourOffer: "Your Offer",
    sendBid: "Send Bid",
    radar: "Radar Active",
    // Login
    login: "Login",
    email: "Email Address",
    password: "Password",
    phoneLabel: "Phone Number",
    forgotPassword: "Forgot password?",
    dontHaveAccount: "Don't have an account?",
    signUp: "Sign Up",
    loginWithPhone: "Phone",
    loginWithEmail: "Email",
    signIn: "Sign In",
    demoClient: "Client Demo",
    demoPro: "Professional Demo",
    // Instagram & Portfolio
    connectPortfolio: "Connect your Portfolio",
    connectPortfolioDesc: "Automatically showcase your best work. We sync photos and videos from your Instagram Professional account.",
    connectBtn: "Connect Instagram",
    connecting: "Connecting...",
    autoSync: "Auto-syncs every 24h",
    instaConnected: "Instagram Connected",
    itemsSynced: "items synced",
    disconnect: "Disconnect",
    noCaption: "No caption provided.",
    postedOn: "Posted on",
    wantService: "I want this service",
    instaPortfolio: "Instagram Portfolio",
    viewInstaBtn: "View Portfolio on Instagram (Reels & Photos)",
    bio: "Bio",
    serviceTimeline: "Service Timeline",
    // Client Dashboard
    liveMarket: "Live Market",
    monitoringBids: "Monitoring professional bids",
    targetBudget: "Target Budget",
    averageOffer: "Average Offer",
    incomingOffers: "Incoming Offers",
    realTime: "Real-time",
    viewPhotos: "View Photos 📸",
    viewFullProfile: "View Full Profile & Reviews",
    budgetFit: "Budget Fit",
    aboveTarget: "Above Target",
    acceptOffer: "Accept Offer",
    // Requests & Actions
    actions: "Actions",
    editRequest: "Edit Request",
    deleteRequest: "Delete",
    pauseMonitoring: "Pause Monitoring",
    resumeMonitoring: "Resume Monitoring",
    goToMarket: "Go to Live Market",
    monitoringPaused: "Monitoring Paused",
    monitoringActive: "Active Monitoring",
    noActiveRequests: "No active requests found.",
    createFirstRequest: "Create your first request",
    selectRequestToView: "Select a request to view the Live Market",
    // Chat
    serviceAgreed: "Service agreed for",
    chatStarted: "Chat started.",
    serviceCompleted: "Service Completed!",
    experienceQuestion: "How was your experience with",
    writeReview: "Write a short review...",
    submitReview: "Submit Review",
    onlineNow: "Online now",
    finishJob: "Finish Job",
    typeMessage: "Type a message...",
    // Landing
    exploreServices: "Explore services near you",
    results: "results",
    noServices: "No services found for",
    clearSearch: "Clear search",
    offerLabel: "Offer",
    // --- NEW: Analytics, Workflow & Guard (DE) ---
    financialPerformance: "Finanzleistung",
    totalEarnings: "Gesamteinnahmen",
    jobsCompleted: "Erledigte Jobs",
    breakdown: "Aufschlüsselung",
    noJobsPeriod: "Keine Jobs für diesen Zeitraum gefunden.",
    filterToday: "HEUTE",
    filterWeek: "WOCHE",
    filterMonth: "MONAT",
    filterYear: "JAHR",
    // Service Status
    statusConfirmed: "Service Bestätigt",
    subConfirmed: "Warten auf den Start der Route.",
    statusEnRoute: "Unterwegs",
    subEnRoute: "Profi fährt zu Ihrem Standort.",
    statusArrived: "Angekommen",
    subArrived: "Profi ist am Standort.",
    statusInProgress: "In Bearbeitung",
    subInProgress: "Service wird durchgeführt.",
    statusCompleted: "Abgeschlossen",
    subCompleted: "Service beendet. Quittung siehe unten.",
    recording: "Aufnahme",
    // Pro Actions
    actionOnWay: "Ich bin unterwegs",
    actionArrived: "Ich bin angekommen",
    actionStart: "Service Starten",
    actionFinish: "Service Beenden",
    // System Messages
    msgOnWay: "🚗 Der Profi ist unterwegs.",
    msgArrived: "📍 Der Profi ist am Standort angekommen.",
    msgStarted: "⏱️ Service gestartet.",
    msgPriceUpdate: "System: Der Servicepreis wurde aktualisiert auf €",
    // Receipt
    receiptTitle: "Servicequittung",
    startTime: "Startzeit",
    endTime: "Endzeit",
    duration: "Dauer",
    total: "Gesamt",
    // Navigation Guard
    leaveNegotiation: "Verhandlung verlassen?",
    leaveNegotiationDesc: "Möchten Sie zum Live-Markt zurückkehren? Dieser Chat wird gespeichert, und Sie können neue Angebote sehen.",
    returnToMarket: "Zum Markt zurück",
    stayHere: "Hier bleiben",
    // Offer Modals
    updateOffer: "Angebot aktualisieren",
    newPrice: "Neuer Preis (€)",
    reasonChange: "Grund der Änderung",
    sendUpdate: "Update senden",
    confirmChange: "Änderung bestätigen?",
    confirmChangeDesc: "Der Servicepreis wird aktualisiert auf",
    confirmChangeSuffix: "Die Differenz wird Ihrer Hauptzahlungsmethode belastet.",
    yesConfirm: "Ja, Bestätigen",
    cancel: "Abbrechen",
    proposalUpdate: "Angebots-Update",
    offerAccepted: "Angebot Angenommen",
    offerDeclined: "Angebot Abgelehnt"
  },
  LB: {
    // ... existing ...
    acceptAndChat: "Akzeptéieren & Chat Opmaachen",
    noCompany: "Nach keng Firma?",
    openCompanyBtn: "Firma opmaachen mat ServiceBid",
    formationTitle: "Firmegrënnung Service",
    formationSubtitle: "Mir këmmeren eis um d'administrativ Schrëtt fir Äre legale Status zu Lëtzebuerg opzebauen.",
    formStep1: "Projet Detailer",
    formStep2: "Dokumenter",
    businessType: "Zielstruktur",
    independantType: "Indépendant (Eenzelbetrib)",
    sarlsType: "SARL-S (Vereinfacht)",
    activityDesc: "Beschreiwung vun der Aktivitéit",
    activityPlace: "Bsp: Molerei, Renovatioun, Elektresch Berodung...",
    residency: "Aktuelle Wunnsëtz",
    residencyLux: "Ech wunnen zu Lëtzebuerg",
    residencyEU: "Ech wunnen an der EU",
    residencyNonEU: "Net-EU Awunner",
    docPassport: "Pass / Identitéitskaart",
    docCriminal: "Strofregisterauszuch (Casier Judiciaire)",
    submitRequest: "Grënnungsufro Schécken",
    requestSent: "Ufro Erfollegräich Geschéckt!",
    requestSentDesc: "Eist juristescht Team iwwerpréift Är Detailer a kontaktéiert Iech bannent 24 Stonnen.",
    backToHome: "Zréck op d'Startsäit",
    welcomeTitle: "Welcome to ServiceBid",
    welcomeSubtitle: "The transparent marketplace for trusted services.",
    imClient: "I'm a Client",
    imClientDesc: "I need a service done.",
    imPro: "I'm a Professional",
    imProDesc: "I want to offer my services.",
    heroTitle: "The service you need, <span class='text-emerald-500'>the way you want.</span>",
    heroSubtitle: "Receive up to 4 quotes from rated professionals in minutes.",
    searchPlaceholder: "Ex: Mechanic, Electrician, Solar...",
    popularCategories: "Popular Categories",
    proCTA: "Are you a professional?",
    proCTADesc: "Increase your revenue by serving clients near you.",
    proCTABtn: "Register my business",
    trustSecure: "Secure",
    trustStars: "4.9/5 Stars",
    trustFast: "Fast",
    // Navigation
    myRequests: "My Requests",
    manageRequests: "Manage your requests and quotes",
    openRequests: "Open Requests",
    historyTab: "History",
    messagesTab: "Messagen",
    noRequests: "No active requests.",
    noRequestsDesc: "Your completed services will appear here.",
    statusWaiting: "Status: Waiting for Quotes",
    received: "Received",
    budgetForYou: "Quotes for you",
    viewDetails: "View Details",
    hireNow: "Hire Now",
    loggedAs: "Logged in as",
    profile: "My Profile",
    dashboard: "Dashboard",
    logout: "Logout",
    stepXofY: "Step {x} of {y}",
    back: "Back",
    next: "Next",
    finish: "Submit Registration",
    saveChanges: "Save Changes",
    // Wizard
    whatNeed: "What do you need?",
    describeProblem: "Describe your problem",
    whereWhen: "Where and when?",
    defineLocation: "Define location and urgency",
    photosOptional: "Photos & Budget",
    helpPro: "Set your budget and add photos",
    titleLabel: "Request Title",
    titlePlaceholder: "Ex: Repair shower wiring",
    detailsLabel: "Details",
    detailsPlaceholder: "Describe what happened, brands, models...",
    addressPlaceholder: "Your address or ZIP code",
    whenLabel: "When?",
    urgencyAsap: "ASAP",
    urgencyThisWeek: "This week",
    urgencyPlanning: "Just researching",
    addPhoto: "Add",
    photoTip: "Photos help professionals provide more accurate quotes and avoid surprises.",
    requestQuotes: "Request Quotes",
    budgetLabel: "Your Budget Estimate",
    budgetPlaceholder: "0",
    budgetHelp: "Enter the amount you are willing to pay for this service.",
    // Profile
    personalInfo: "Personal Info",
    addressLogistics: "Address & Logistics",
    security: "Security",
    manageIdentity: "Manage your identity and communication languages.",
    smartAddress: "Smart address engine based on Luxembourg registry.",
    logisticsNote: "Logistics Note",
    luxNoteDesc: "In Luxembourg, specifying elevator and parking helps providers organize better.",
    languages: "Languages",
    personalDetails: "Identity & Residence",
    businessDetails: "Legal Structure",
    licenseDetails: "Business License",
    bankDetails: "Bank Details",
    reviewDetails: "Review & Sign",
    fullName: "Full Name",
    cnsNumber: "Social Security (CNS) - 13 digits",
    address: "Address",
    street: "Street",
    houseNumber: "Number",
    postalCode: "Postal Code (L-XXXX)",
    locality: "Locality",
    idUpload: "ID Card / Residence Permit",
    legalType: "Legal Entity Type",
    independant: "Independent",
    societe: "Company (SARL/SA)",
    rcsNumber: "RCS Number",
    tvaNumber: "VAT Number (LU + 8 digits)",
    companyName: "Company Name",
    licenseUpload: "Establishment Authorization",
    licenseNum: "License Number",
    licenseExpiry: "Validity Date",
    iban: "IBAN (SEPA)",
    accHolder: "Account Holder",
    declaration: "I declare that the information is true and I am authorized to work in the Grand Duchy.",
    memberSince: "Member since",
    rating: "Rating",
    jobs: "Jobs",
    xp: "XP",
    // Categories
    Cleaning: "Cleaning",
    Electrician: "Electrician",
    Plumbing: "Plumbing",
    Gardening: "Gardening",
    "IT Support": "IT Support",
    Moving: "Moving",
    Beauty: "Beauty",
    "Pet Sitter": "Pet Sitter",
    Mechanic: "Mechanic (Car/Bike)",
    ElectricVehicle: "Electric Car Specialist",
    AutoBody: "Auto Body & Paint",
    Micromobility: "Scooters & E-Bikes",
    SolarEnergy: "Solar & Batteries",
    // Pro Dashboard
    nearby: "Nearby Requests",
    yourOffer: "Your Offer",
    sendBid: "Send Bid",
    radar: "Radar Active",
    // Login
    login: "Login",
    email: "Email Address",
    password: "Password",
    phoneLabel: "Phone Number",
    forgotPassword: "Forgot password?",
    dontHaveAccount: "Don't have an account?",
    signUp: "Sign Up",
    loginWithPhone: "Phone",
    loginWithEmail: "Email",
    signIn: "Sign In",
    demoClient: "Client Demo",
    demoPro: "Professional Demo",
    // Instagram & Portfolio
    connectPortfolio: "Connect your Portfolio",
    connectPortfolioDesc: "Automatically showcase your best work. We sync photos and videos from your Instagram Professional account.",
    connectBtn: "Connect Instagram",
    connecting: "Connecting...",
    autoSync: "Auto-syncs every 24h",
    instaConnected: "Instagram Connected",
    itemsSynced: "items synced",
    disconnect: "Disconnect",
    noCaption: "No caption provided.",
    postedOn: "Posted on",
    wantService: "I want this service",
    instaPortfolio: "Instagram Portfolio",
    viewInstaBtn: "View Portfolio on Instagram (Reels & Photos)",
    bio: "Bio",
    serviceTimeline: "Service Timeline",
    // Client Dashboard
    liveMarket: "Live Market",
    monitoringBids: "Monitoring professional bids",
    targetBudget: "Target Budget",
    averageOffer: "Average Offer",
    incomingOffers: "Incoming Offers",
    realTime: "Real-time",
    viewPhotos: "View Photos 📸",
    viewFullProfile: "View Full Profile & Reviews",
    budgetFit: "Budget Fit",
    aboveTarget: "Above Target",
    acceptOffer: "Accept Offer",
    // Requests & Actions
    actions: "Actions",
    editRequest: "Edit Request",
    deleteRequest: "Delete",
    pauseMonitoring: "Pause Monitoring",
    resumeMonitoring: "Resume Monitoring",
    goToMarket: "Go to Live Market",
    monitoringPaused: "Monitoring Paused",
    monitoringActive: "Active Monitoring",
    noActiveRequests: "No active requests found.",
    createFirstRequest: "Create your first request",
    selectRequestToView: "Select a request to view the Live Market",
    // Chat
    serviceAgreed: "Service agreed for",
    chatStarted: "Chat started.",
    serviceCompleted: "Service Completed!",
    experienceQuestion: "How was your experience with",
    writeReview: "Write a short review...",
    submitReview: "Submit Review",
    onlineNow: "Online now",
    finishJob: "Finish Job",
    typeMessage: "Type a message...",
    // Landing
    exploreServices: "Explore services near you",
    results: "results",
    noServices: "No services found for",
    clearSearch: "Clear search",
    offerLabel: "Offer",
    // --- NEW: Analytics, Workflow & Guard (LB) ---
    financialPerformance: "Finanziell Leeschtung",
    totalEarnings: "Gesamtakommes",
    jobsCompleted: "Ofgeschloss Aarbechten",
    breakdown: "Detailer",
    noJobsPeriod: "Keng Aarbechten an dëser Period fonnt.",
    filterToday: "HAUT",
    filterWeek: "WOCH",
    filterMonth: "MOUNT",
    filterYear: "JOER",
    // Service Status
    statusConfirmed: "Service Bestätegt",
    subConfirmed: "Waart op de Start vun der Route.",
    statusEnRoute: "Um Wee",
    subEnRoute: "De Profi ass ënnerwee bei Iech.",
    statusArrived: "Ukomm",
    subArrived: "De Profi ass op der Plaz.",
    statusInProgress: "Am Gaang",
    subInProgress: "Service gëtt duerchgefouert.",
    statusCompleted: "Ofgeschloss",
    subCompleted: "Service fäerdeg. Kuckt de Reçu hei ënnen.",
    recording: "Opnam",
    // Pro Actions
    actionOnWay: "Ech sinn um Wee",
    actionArrived: "Ech sinn ukomm",
    actionStart: "Service Starten",
    actionFinish: "Service Ofschléissen",
    // System Messages
    msgOnWay: "🚗 De Profi ass um Wee.",
    msgArrived: "📍 De Profi ass ukomm.",
    msgStarted: "⏱️ Service gestart.",
    msgPriceUpdate: "System: De Präis gouf aktualiséiert op €",
    // Receipt
    receiptTitle: "Service Reçu",
    startTime: "Startzäit",
    endTime: "Endzäit",
    duration: "Dauer",
    total: "Total",
    // Navigation Guard
    leaveNegotiation: "Verhandlung verloossen?",
    leaveNegotiationDesc: "Wëllt Dir zréck op de Live Maart? Dësen Chat gëtt gespäichert, an Dir kënnt nei Offere gesinn.",
    returnToMarket: "Zréck op de Maart",
    stayHere: "Hei bleiwen",
    // Offer Modals
    updateOffer: "Offer aktualiséieren",
    newPrice: "Neie Präis (€)",
    reasonChange: "Grond fir Ännerung",
    sendUpdate: "Update schécken",
    confirmChange: "Ännerung bestätegen?",
    confirmChangeDesc: "De Präis gëtt aktualiséiert op",
    confirmChangeSuffix: "Den Ënnerscheed gëtt vun Ärer Haaptbezuelmethod ofgebucht.",
    yesConfirm: "Jo, Bestätegen",
    cancel: "Ofbriechen",
    proposalUpdate: "Propositioun Update",
    offerAccepted: "Offer Ugeholl",
    offerDeclined: "Offer Ofgeleent"
  }
};

type Translations = typeof TRANSLATIONS.EN;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
  tCategory: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('FR');

  const t = TRANSLATIONS[language];

  const tCategory = (key: string) => {
    return (t as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tCategory }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
