
import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'EN' | 'FR' | 'DE' | 'LB' | 'PT';

export const LANGUAGES_LIST: { code: Language; label: string; flag: string }[] = [
  { code: 'FR', label: 'Français', flag: '🇫🇷' },
  { code: 'EN', label: 'English', flag: '🇬🇧' },
  { code: 'PT', label: 'Português', flag: '🇧🇷' },
  { code: 'DE', label: 'Deutsch', flag: '🇩🇪' },
  { code: 'LB', label: 'Lëtzebuergesch', flag: '🇱🇺' },
];

const enTranslations = {
    // ... EXISTING KEYS ...
    signIn: "Sign In",
    welcomeSubtitle: "Welcome back to ServiceBid",
    imClient: "I'm a Client",
    imPro: "I'm a Pro",
    myWebsite: "My Website",
    siteStatus: "Site Status",
    online: "ONLINE",
    offline: "OFFLINE",
    copyLink: "Copy Link",
    shareWhatsapp: "Share on WhatsApp",
    appearance: "Appearance",
    selectTheme: "Select Theme",
    accentColor: "Accent Color",
    previewSite: "PREVIEW MY SITE",
    siteInfo: "Did you know?",
    siteInfoDesc: "Your site content (Photos, Reviews, Bio) is automatically synced from your Profile. No need to edit twice!",
    themeModern: "Modern",
    themeClassic: "Classic",
    themeBold: "Bold",
    themeMinimal: "Minimal",
    visitExternal: "Open in Browser",
    linkCopied: "Link Copied!",
    loginWithEmail: "Email",
    loginWithPhone: "Phone",
    email: "Email",
    phoneLabel: "Phone Number",
    password: "Password",
    forgotPassword: "Forgot Password?",
    dontHaveAccount: "Don't have an account?",
    signUp: "Sign Up",
    loggedAs: "Logged in as",
    dashboard: "Dashboard",
    profile: "Profile",
    logout: "Logout",
    personalDetails: "Personal Details",
    businessDetails: "Business Details",
    servicesAndScope: "Services & Scope",
    licenseDetails: "License Details",
    financialPlan: "Financial Plan",
    reviewDetails: "Review Details",
    fullName: "Full Name",
    cnsNumber: "CNS Number",
    street: "Street",
    houseNumber: "Number",
    postalCode: "Postal Code",
    locality: "Locality",
    idUpload: "Upload ID Card",
    independant: "Independente",
    societe: "Company (S.à r.l.)",
    companyName: "Company Name",
    tvaNumber: "VAT Number",
    rcsNumber: "RCS Number",
    selectServices: "Select your Services",
    selectServicesDesc: "Choose the categories you work in",
    licenseNum: "License Number",
    licenseExpiry: "License Expiry",
    planSelect: "Select your Plan",
    founderOffer: "Founder Offer",
    premiumPlan: "Premium Plan",
    lifetimeAccess: "Lifetime Access",
    benefitSite: "Pro Website + SEO",
    benefitPriority: "Search Priority",
    benefitFees: "0% Commission Fees",
    benefitSupport: "Dedicated Support",
    benefitBadge: "Founding Member Badge",
    durationLabel: "Duration:",
    freeForever: "Free Forever",
    basicPlan: "Basic Plan",
    basicDesc: "Standard platform access",
    payoutDetails: "Payout Details",
    iban: "IBAN",
    accHolder: "Account Holder",
    paymentMethod: "Payment Method",
    expiryDate: "MM/YY",
    cvc: "CVC",
    cardHolder: "Card Holder",
    websiteReady: "Website Ready!",
    websiteDesc: "Your professional site is ready.",
    visitSite: "Visit Site",
    generatedFor: "Generated for",
    declaration: "I declare the information is correct.",
    back: "Back",
    next: "Next",
    finish: "Finish",
    heroTitle: "Find the best <span class='text-emerald-500'>pros</span> in Luxembourg",
    heroSubtitle: "Get quotes in minutes for cleaning, renovation, moving and more.",
    searchPlaceholder: "What do you need help with?",
    trustSecure: "Verified Pros",
    trustStars: "Top Rated",
    trustFast: "Quick Quotes",
    popularCategories: "Popular Categories",
    exploreServices: "Explore our services",
    results: "Results",
    noServices: "No services found for",
    clearSearch: "Clear search",
    proCTA: "Are you a Pro?",
    proCTADesc: "Join the network and grow your business.",
    proCTABtn: "Register as Pro",
    noCompany: "No Company?",
    openCompanyHelpBtn: "We help you start",
    openCompanyBtn: "Start Company",
    whatNeed: "What do you need?",
    describeProblem: "Describe your request",
    whereWhen: "Where & When?",
    defineLocation: "Location and timing",
    photosOptional: "Photos (Optional)",
    helpPro: "Help pros understand better",
    stepXofY: "Step {x} of {y}",
    titleLabel: "Title",
    titlePlaceholder: "e.g. Leaking faucet",
    detailsLabel: "Details",
    detailsPlaceholder: "Describe the issue...",
    addressPlaceholder: "Enter address",
    whenLabel: "When?",
    urgencyAsap: "As soon as possible",
    urgencyThisWeek: "This week",
    urgencyPlanning: "Planning phase",
    budgetLabel: "Budget",
    budgetPlaceholder: "Estimated budget",
    budgetHelp: "This helps pros give better quotes",
    addPhoto: "Add Photo",
    photoTip: "Photos help get more accurate quotes",
    requestQuotes: "Request Quotes",
    saveChanges: "Save Changes",
    myRequests: "My Requests",
    manageRequests: "Manage your service requests",
    createFirstRequest: "Create Request",
    noActiveRequests: "No active requests",
    goToMarket: "Go to Market",
    editRequest: "Edit",
    deleteRequest: "Delete",
    monitoringPaused: "Paused",
    monitoringActive: "Live",
    resumeMonitoring: "Resume",
    pauseMonitoring: "Pause",
    realTime: "Real Time",
    targetBudget: "Target Budget",
    averageOffer: "Avg Offer",
    incomingOffers: "Incoming Offers",
    viewPhotos: "Photos",
    viewFullProfile: "Full Profile",
    acceptOffer: "Accept",
    budgetFit: "Good Fit",
    aboveTarget: "Above Target",
    selectRequestToView: "Select a request to view market",
    historyTab: "History",
    noRequestsDesc: "No history available",
    financialPerformance: "Financial Dashboard",
    filterToday: "Today",
    filterWeek: "Last 7 Days",
    filterMonth: "Last 30 Days",
    filterYear: "This Year",
    totalEarnings: "Gross Revenue",
    jobsCompleted: "Jobs",
    breakdown: "Transactions",
    noJobsPeriod: "No transactions in this period",
    messagesTab: "Messages",
    radar: "Radar",
    nearby: "Nearby",
    offerLabel: "Offer",
    yourOffer: "Your Offer",
    acceptAndChat: "Accept & Chat",
    serviceAgreed: "Service agreed at",
    chatStarted: "Chat started.",
    msgOnWay: "I am on my way.",
    msgArrived: "I have arrived.",
    msgStarted: "Service started.",
    msgPriceUpdate: "Price updated to",
    proposalUpdate: "Proposal Update",
    offerAccepted: "Offer Accepted",
    offerDeclined: "Offer Declined",
    receiptTitle: "Receipt",
    startTime: "Start Time",
    endTime: "End Time",
    duration: "Duration",
    total: "Total",
    actionOnWay: "On My Way",
    actionArrived: "Arrived",
    actionStart: "Start Job",
    actionFinish: "Finish Job",
    serviceCompleted: "Service Completed",
    experienceQuestion: "How was your experience with",
    writeReview: "Write a review...",
    submitReview: "Submit Review",
    finishJob: "Generate Invoice & Finish",
    onlineNow: "Online",
    typeMessage: "Type a message...",
    leaveNegotiation: "Leave Negotiation?",
    leaveNegotiationDesc: "You have an active negotiation.",
    returnToMarket: "Return to Market",
    stayHere: "Stay Here",
    updateOffer: "Update Offer",
    newPrice: "New Price",
    reasonChange: "Reason for change",
    sendUpdate: "Send Update",
    confirmChange: "Confirm Change",
    confirmChangeDesc: "Do you accept the price of",
    confirmChangeSuffix: "?",
    yesConfirm: "Yes, Confirm",
    cancel: "Cancel",
    personalInfo: "Personal Info",
    companyData: "Company Data",
    addressLogistics: "Address & Logistics",
    security: "Security",
    logisticsNote: "Logistics",
    luxNoteDesc: "Luxembourg logistics info",
    companyDesc: "Manage your company details",
    cantEditHelp: "Some fields are read-only",
    legalForm: "Legal Form",
    govAuth: "Gov Authorization",
    banking: "Banking",
    manageIdentity: "Manage Identity",
    languages: "Languages",
    smartAddress: "Smart Address",
    connectPortfolio: "Connect Instagram",
    connectPortfolioDesc: "Showcase your work directly from Instagram",
    connecting: "Connecting...",
    connectBtn: "Connect",
    autoSync: "Auto Sync",
    instaConnected: "Instagram Connected",
    itemsSynced: "items synced",
    disconnect: "Disconnect",
    noCaption: "No caption",
    postedOn: "Posted on",
    wantService: "I want this service",
    rating: "Rating",
    jobs: "Jobs",
    xp: "XP",
    speaks: "Speaks",
    serviceLocation: "Service Location",
    openMaps: "Open Maps",
    bio: "Bio",
    serviceTimeline: "Service Timeline",
    hireNow: "Hire Now",
    viewInstaBtn: "View Portfolio",
    statusConfirmed: "Confirmed",
    subConfirmed: "Pro is scheduled",
    statusEnRoute: "En Route",
    subEnRoute: "Pro is on the way",
    statusArrived: "Arrived",
    subArrived: "Pro is at location",
    statusInProgress: "In Progress",
    subInProgress: "Service is running",
    statusCompleted: "Completed",
    subCompleted: "Service finished",
    recording: "Recording",
    clientRole: "Client",
    reliableClient: "Reliable",
    requestsMade: "Requests",
    paymentRate: "Payment Rate",
    subscription: "Subscription & Billing",
    currentPlan: "Current Plan",
    paymentCard: "Payment Card",
    changeCard: "Change Card",
    availBalance: "Available Balance",
    pendingBalance: "Pending",
    vatEstimate: "VAT Estimate (17%)",
    exportReport: "Export Fiscal Report",
    downloadPdf: "Download PDF",
    invoiceNo: "Invoice N°",
    client: "Client",
    service: "Service",
    amountHT: "Net (HT)",
    amountTTC: "Total (TTC)",
    upgradePro: "Upgrade to PRO",
    upgradeDesc: "Automate your accounting with compliant Luxembourgish invoices.",
    invBillTo: "Bill To",
    invDate: "Invoice Date",
    invDue: "Due Date",
    invDesc: "Description",
    invQty: "Qty",
    invRate: "Rate",
    invTotal: "Total",
    invSubtotal: "Subtotal (HT)",
    invVatAmt: "VAT Amount",
    invTotalDue: "Total Due (TTC)",
    invFooter: "Payment due within 14 days. Please include invoice number in transfer reference.",
    businessHours: "Business Hours",
    openingTime: "Opening Time",
    closingTime: "Closing Time",
    workingDays: "Working Days",
    addToFavorites: "Add to Favorites",
    removeFromFavorites: "Remove Favorite",
    blockContact: "Block Business",
    unblockContact: "Unblock",
    blockedUsers: "Blocked Users",
    noBlockedUsers: "No blocked users.",
    favoritesTab: "Favorites",
    noFavorites: "No favorites yet.",
    contactInfo: "Contact Info",
    onlinePresence: "Online & Social",
    startDate: "From",
    endDate: "To",
    customRange: "Custom Range",
    revenueTrend: "Revenue Trend",
    averageValue: "Avg Ticket",
    confirmWorkDone: "Is the job done?",
    confirmWorkDoneDesc: "Pro has marked the job as finished. Please confirm.",
    yesFinished: "Yes, Finished",
    noNotYet: "No, Not Yet",
    confirmPayment: "Did you receive payment?",
    confirmPaymentDesc: "Client has confirmed. Did you get paid?",
    yesReceived: "Yes, Payment Received",
    quickTags: "Quick Feedback",
    tagPunctual: "Punctual",
    tagClean: "Clean Work",
    tagPro: "Professional",
    tagFriendly: "Friendly",
    tagFair: "Fair Price",
    chatArchived: "Chat Archived",
    reopenChat: "Reopen Chat",
    waitingClient: "Waiting for Client...",
    waitingPayment: "Waiting for Payment...",
    liveFeed: "Live Feed",
    opportunities: "Opportunities",
    roleLabel: "Role:",
    quickAccess: "Quick Access (Demo)",
    orLoginManual: "Or login manual",
    licenseInfo: "This license is issued by the Ministry of the Economy. Mandatory for most activities in LU.",
    uploadPdf: "Upload PDF / Photo",
    attached: "Document Attached",
    newAddress: "New Address",
    liveMarket: "Live Market",
    instaPortfolio: "Instagram Portfolio",
    jobClosed: "Job Closed & Archived.",
    invoiceGen: "Invoice Generated. Waiting for client confirmation.",
    chatReopened: "Chat Reopened.",
    // SMART REPLY & MISSING KEYS
    chatSettings: "Chat Settings",
    smartReply: "Smart Reply",
    smartReplyDesc: "Auto-reply when you are busy or driving.",
    activationTime: "Activate if no reply in:",
    immediate: "Immediately",
    mins5: "5 Minutes",
    mins15: "15 Minutes",
    botPersonality: "Bot Personality",
    agilityMode: "Agility (Focus on Speed)",
    agilityDesc: "Inform that you are driving and will reply soon.",
    dataMode: "Data Collection (Recommended)",
    dataDesc: "Ask for photos and details to speed up the quote.",
    customMode: "Custom Message",
    customDesc: "Write your own welcome message.",
    botMsgFooter: "Automated reply - Pro notified.",
    enableAutoReply: "Enable automated responses",
    preview: "Preview",
    yourMessage: "Your Message",
    financialErp: "Financial (ERP)",
    scanningJobs: "Scanning for jobs...",
    upgradeNow: "Upgrade Now",
    upgradeBtn: "Upgrade",
    stepIndicator: "Step {step} of {total}",
    uploadPdfLabel: "Upload PDF / Photo",
    licenseUploaded: "LICENSE_UPLOADED.PDF",
    summaryServices: "Services",
    summaryPlan: "Plan",
    summaryIban: "IBAN",
    trustedPros: "Your trusted professionals.",
    navRequests: "Requests",
    navMarket: "Market",
    navChat: "Chat",
    navFavs: "Favs",
    activePlan: "(Active)",
    closedDay: "Closed",
    paymentValidation: "Required for subscription validation. You won't be charged today.",
    botMessageAgility: "Hello! I'm the virtual assistant. The professional is currently driving or working. He has received your request and will reply personally ASAP!",
    botMessageData: "Thanks for choosing us! I'm finishing a job right now. To speed things up, could you send photos or describe the issue in more detail here? I'll reply shortly.",
    botMessageCustomDefault: "Welcome! I will be with you shortly."
};

const ptTranslations: typeof enTranslations = {
    // ... EXISTING KEYS ...
    signIn: "Entrar",
    welcomeSubtitle: "Bem-vindo de volta ao ServiceBid",
    imClient: "Sou Cliente",
    imPro: "Sou Profissional",
    myWebsite: "Meu Site",
    siteStatus: "Status do Site",
    online: "ONLINE",
    offline: "OFFLINE",
    copyLink: "Copiar Link",
    shareWhatsapp: "Enviar no WhatsApp",
    appearance: "Aparência",
    selectTheme: "Escolher Tema",
    accentColor: "Cor de Destaque",
    previewSite: "VISUALIZAR MEU SITE 👁️",
    siteInfo: "Você sabia?",
    siteInfoDesc: "O conteúdo do seu site (Fotos, Textos, Contato) é puxado automaticamente do seu Perfil. Para alterar informações, edite seus Dados Pessoais ou Portfólio.",
    themeModern: "Moderno",
    themeClassic: "Clássico",
    themeBold: "Bold",
    themeMinimal: "Minimal",
    visitExternal: "Abrir no Navegador",
    linkCopied: "Link Copiado!",
    loginWithEmail: "E-mail",
    loginWithPhone: "Celular",
    email: "E-mail",
    phoneLabel: "Número de Celular",
    password: "Senha",
    forgotPassword: "Esqueceu a senha?",
    dontHaveAccount: "Não tem uma conta?",
    signUp: "Cadastre-se",
    loggedAs: "Logado como",
    dashboard: "Painel",
    profile: "Perfil",
    logout: "Sair",
    personalDetails: "Dados Pessoais",
    businessDetails: "Dados da Empresa",
    servicesAndScope: "Atuação e Serviços",
    licenseDetails: "Licença",
    financialPlan: "Financeiro e Planos",
    reviewDetails: "Revisão",
    fullName: "Nome Completo",
    cnsNumber: "Número CNS",
    street: "Rua",
    houseNumber: "Número",
    postalCode: "Código Postal",
    locality: "Localidade",
    idUpload: "Enviar Documento",
    independant: "Independente",
    societe: "Sociedade (S.à r.l.)",
    companyName: "Nome da Empresa",
    tvaNumber: "Número IVA",
    rcsNumber: "Número RCS",
    selectServices: "Selecione seus Serviços",
    selectServicesDesc: "Escolha as categorias que você atende",
    licenseNum: "Número da Licença",
    licenseExpiry: "Validade da Licença",
    planSelect: "Selecione seu Plano",
    founderOffer: "OFERTA FUNDADOR",
    premiumPlan: "Plano Premium",
    lifetimeAccess: "Acesso Vitalício",
    benefitSite: "Site Pro + SEO",
    benefitPriority: "Destaque na Busca",
    benefitFees: "0% de Comissão",
    benefitSupport: "Suporte Dedicado",
    benefitBadge: "Selo Fundador",
    durationLabel: "Duração:",
    freeForever: "Grátis para Sempre",
    basicPlan: "Plano Básico",
    basicDesc: "Acesso padrão à plataforma",
    payoutDetails: "Dados de Recebimento",
    iban: "IBAN",
    accHolder: "Titular da Conta",
    paymentMethod: "Forma de Pagamento",
    expiryDate: "MM/AA",
    cvc: "CVC",
    cardHolder: "Nome no Cartão",
    websiteReady: "Site Pronto!",
    websiteDesc: "Seu site profissional está pronto.",
    visitSite: "Ver Site",
    generatedFor: "Gerado para",
    declaration: "Declaro que as informações estão corretas.",
    back: "Voltar",
    next: "Próximo",
    finish: "Finalizar",
    heroTitle: "Encontre os melhores <span class='text-emerald-500'>profissionais</span> em Luxemburgo",
    heroSubtitle: "Orçamentos em minutos para limpeza, obras, mudanças e mais.",
    searchPlaceholder: "O que você precisa?",
    trustSecure: "Pros Verificados",
    trustStars: "Bem Avaliados",
    trustFast: "Rápido",
    popularCategories: "Categorias Populares",
    exploreServices: "Explore nossos serviços",
    results: "Resultados",
    noServices: "Nenhum serviço para",
    clearSearch: "Limpar busca",
    proCTA: "Você é Profissional?",
    proCTADesc: "Junte-se à rede e cresça seu negócio.",
    proCTABtn: "Cadastrar como Pro",
    noCompany: "Sem Empresa?",
    openCompanyHelpBtn: "Nós ajudamos",
    openCompanyBtn: "Abrir Empresa",
    whatNeed: "O que você precisa?",
    describeProblem: "Descreva seu pedido",
    whereWhen: "Onde e Quando?",
    defineLocation: "Local e horário",
    photosOptional: "Fotos (Opcional)",
    helpPro: "Ajude os pros a entender",
    stepXofY: "Passo {x} de {y}",
    titleLabel: "Título",
    titlePlaceholder: "ex: Torneira vazando",
    detailsLabel: "Detalhes",
    detailsPlaceholder: "Descreva o problema...",
    addressPlaceholder: "Digite o endereço",
    whenLabel: "Para quando?",
    urgencyAsap: "O quanto antes",
    urgencyThisWeek: "Esta semana",
    urgencyPlanning: "Planejamento",
    budgetLabel: "Orçamento",
    budgetPlaceholder: "Orçamento estimado",
    budgetHelp: "Ajuda a receber propostas melhores",
    addPhoto: "Adicionar Foto",
    photoTip: "Fotos ajudam a ter orçamentos precisos",
    requestQuotes: "Pedir Orçamentos",
    saveChanges: "Salvar Alterações",
    myRequests: "Meus Pedidos",
    manageRequests: "Gerencie seus pedidos de serviço",
    createFirstRequest: "Criar Pedido",
    noActiveRequests: "Nenhum pedido ativo",
    goToMarket: "Ir ao Mercado",
    editRequest: "Editar",
    deleteRequest: "Excluir",
    monitoringPaused: "Pausado",
    monitoringActive: "Ao Vivo",
    resumeMonitoring: "Retomar",
    pauseMonitoring: "Pausar",
    realTime: "Tempo Real",
    targetBudget: "Orçamento Alvo",
    averageOffer: "Oferta Média",
    incomingOffers: "Ofertas Recebidas",
    viewPhotos: "Fotos",
    viewFullProfile: "Perfil Completo",
    acceptOffer: "Aceitar",
    budgetFit: "No Preço",
    aboveTarget: "Acima",
    selectRequestToView: "Selecione um pedido para ver o mercado",
    historyTab: "Histórico",
    noRequestsDesc: "Sem histórico disponível",
    financialPerformance: "Painel Financeiro",
    filterToday: "Hoje",
    filterWeek: "Últ. 7 Dias",
    filterMonth: "Últ. 30 Dias",
    filterYear: "Este Ano",
    totalEarnings: "Faturamento Bruto",
    jobsCompleted: "Jobs",
    breakdown: "Transações",
    noJobsPeriod: "Sem transações neste período",
    messagesTab: "Mensagens",
    radar: "Radar",
    nearby: "Próximos",
    offerLabel: "Oferta",
    yourOffer: "Sua Oferta",
    acceptAndChat: "Aceitar e Conversar",
    serviceAgreed: "Serviço acordado por",
    chatStarted: "Chat iniciado.",
    msgOnWay: "Estou a caminho.",
    msgArrived: "Cheguei ao local.",
    msgStarted: "Serviço iniciado.",
    msgPriceUpdate: "Preço atualizado para",
    proposalUpdate: "Atualização de Proposta",
    offerAccepted: "Oferta Aceita",
    offerDeclined: "Oferta Recusada",
    receiptTitle: "Recibo",
    startTime: "Início",
    endTime: "Fim",
    duration: "Duração",
    total: "Total",
    actionOnWay: "A Caminho",
    actionArrived: "Cheguei",
    actionStart: "Iniciar",
    actionFinish: "Finalizar",
    serviceCompleted: "Serviço Concluído",
    experienceQuestion: "Como foi sua experiência com",
    writeReview: "Escreva uma avaliação...",
    submitReview: "Enviar Avaliação",
    finishJob: "Gerar Fatura & Finalizar",
    onlineNow: "Online",
    typeMessage: "Digite uma mensagem...",
    leaveNegotiation: "Sair da Negociação?",
    leaveNegotiationDesc: "Você tem uma negociação ativa.",
    returnToMarket: "Voltar ao Mercado",
    stayHere: "Ficar Aqui",
    updateOffer: "Atualizar Oferta",
    newPrice: "Novo Preço",
    reasonChange: "Motivo da alteração",
    sendUpdate: "Enviar",
    confirmChange: "Confirmar Mudança",
    confirmChangeDesc: "Você aceita o preço de",
    confirmChangeSuffix: "?",
    yesConfirm: "Sim, Confirmar",
    cancel: "Cancelar",
    personalInfo: "Dados Pessoais",
    companyData: "Dados da Empresa",
    addressLogistics: "Endereço e Logística",
    security: "Segurança",
    logisticsNote: "Logística",
    luxNoteDesc: "Info logística Luxemburgo",
    companyDesc: "Gerenciar detalhes da empresa",
    cantEditHelp: "Alguns campos são somente leitura",
    legalForm: "Forma Legal",
    govAuth: "Aut. Governamental",
    banking: "Bancário",
    manageIdentity: "Gerenciar Identidade",
    languages: "Idiomas",
    smartAddress: "Endereço Inteligente",
    connectPortfolio: "Conectar Instagram",
    connectPortfolioDesc: "Mostre seu trabalho direto do Instagram",
    connecting: "Conectando...",
    connectBtn: "Conectar",
    autoSync: "Sinc. Auto",
    instaConnected: "Instagram Conectado",
    itemsSynced: "itens sincronizados",
    disconnect: "Desconectar",
    noCaption: "Sem legenda",
    postedOn: "Postado em",
    wantService: "Quero este serviço",
    rating: "Avaliação",
    jobs: "Jobs",
    xp: "XP",
    speaks: "Fala",
    serviceLocation: "Local do Serviço",
    openMaps: "Abrir Mapa",
    bio: "Bio",
    serviceTimeline: "Linha do Tempo",
    hireNow: "Contratar",
    viewInstaBtn: "Ver Portfólio",
    statusConfirmed: "Confirmado",
    subConfirmed: "Pro agendado",
    statusEnRoute: "A Caminho",
    subEnRoute: "Pro está a caminho",
    statusArrived: "Chegou",
    subArrived: "Pro no local",
    statusInProgress: "Em Andamento",
    subInProgress: "Serviço rodando",
    statusCompleted: "Concluído",
    subCompleted: "Serviço finalizado",
    recording: "Gravando",
    clientRole: "Cliente",
    reliableClient: "Confiável",
    requestsMade: "Pedidos",
    paymentRate: "Pagamentos",
    subscription: "Assinatura e Faturamento",
    currentPlan: "Plano Atual",
    paymentCard: "Cartão de Pagamento",
    changeCard: "Alterar Cartão",
    availBalance: "Saldo Disponível",
    pendingBalance: "A Receber",
    vatEstimate: "Estimativa IVA (17%)",
    exportReport: "Exportar Relatório",
    downloadPdf: "Baixar PDF",
    invoiceNo: "Fatura N°",
    client: "Cliente",
    service: "Serviço",
    amountHT: "Valor (HT)",
    amountTTC: "Total (TTC)",
    upgradePro: "Mude para o PRO",
    upgradeDesc: "Automatize sua contabilidade com faturas luxemburguesas compatíveis.",
    invBillTo: "Faturar Para",
    invDate: "Data da Fatura",
    invDue: "Vencimento",
    invDesc: "Descrição",
    invQty: "Qtd",
    invRate: "Taxa",
    invTotal: "Total",
    invSubtotal: "Subtotal (HT)",
    invVatAmt: "Valor IVA",
    invTotalDue: "Total a Pagar (TTC)",
    invFooter: "Pagamento em até 14 dias. Por favor, inclua o número da fatura na transferência.",
    businessHours: "Horário de Funcionamento",
    openingTime: "Abertura",
    closingTime: "Fechamento",
    workingDays: "Dias de Funcionamento",
    addToFavorites: "Favoritar",
    removeFromFavorites: "Remover Favorito",
    blockContact: "Bloquear Empresa",
    unblockContact: "Desbloquear",
    blockedUsers: "Bloqueados",
    noBlockedUsers: "Nenhum usuário bloqueado.",
    favoritesTab: "Favoritos",
    noFavorites: "Nenhum favorito ainda.",
    contactInfo: "Dados do Contato",
    onlinePresence: "Social e Web",
    startDate: "De",
    endDate: "Até",
    customRange: "Intervalo Personalizado",
    revenueTrend: "Tendência de Receita",
    averageValue: "Ticket Médio",
    confirmWorkDone: "O serviço foi feito?",
    confirmWorkDoneDesc: "O Pro marcou como terminado. Confirme por favor.",
    yesFinished: "Sim, Finalizado",
    noNotYet: "Não, Ainda Não",
    confirmPayment: "Recebeu o pagamento?",
    confirmPaymentDesc: "Cliente confirmou. Você recebeu o valor?",
    yesReceived: "Sim, Recebido",
    quickTags: "Feedback Rápido",
    tagPunctual: "Pontual",
    tagClean: "Limpeza",
    tagPro: "Profissional",
    tagFriendly: "Simpático",
    tagFair: "Preço Justo",
    chatArchived: "Chat Arquivado",
    reopenChat: "Reabrir Chat",
    waitingClient: "Aguardando Cliente...",
    waitingPayment: "Aguardando Pagamento...",
    liveFeed: "Feed ao Vivo",
    opportunities: "Oportunidades",
    roleLabel: "Função:",
    quickAccess: "Acesso Rápido (Demo)",
    orLoginManual: "Ou login manual",
    licenseInfo: "Licença emitida pelo Ministério da Economia. Obrigatória para a maioria das atividades em LU.",
    uploadPdf: "Enviar PDF / Foto",
    attached: "Documento Anexado",
    newAddress: "Novo Endereço",
    liveMarket: "Mercado ao Vivo",
    instaPortfolio: "Portfólio Instagram",
    jobClosed: "Trabalho Encerrado e Arquivado.",
    invoiceGen: "Fatura Gerada. Aguardando confirmação do cliente.",
    chatReopened: "Chat Reaberto.",
    // SMART REPLY
    chatSettings: "Config. de Chat",
    smartReply: "Resposta Inteligente",
    smartReplyDesc: "Resposta automática quando você estiver dirigindo ou ocupado.",
    activationTime: "Ativar se não responder em:",
    immediate: "Imediato",
    mins5: "5 Minutos",
    mins15: "15 Minutos",
    botPersonality: "Personalidade do Bot",
    agilityMode: "Agilidade (Foco em Velocidade)",
    agilityDesc: "Informa que você está dirigindo e responderá em breve.",
    dataMode: "Coleta de Dados (Recomendado)",
    dataDesc: "Pede fotos e detalhes para agilizar o orçamento.",
    customMode: "Mensagem Personalizada",
    customDesc: "Escreva sua própria mensagem de boas-vindas.",
    botMsgFooter: "Resposta automática - Profissional notificado.",
    // MISSING KEYS TRANSLATION
    enableAutoReply: "Ativar respostas automáticas",
    preview: "Pré-visualização",
    yourMessage: "Sua Mensagem",
    financialErp: "Financeiro (ERP)",
    scanningJobs: "Procurando trabalhos...",
    upgradeNow: "Fazer Upgrade Agora",
    upgradeBtn: "Upgrade",
    stepIndicator: "Passo {step} de {total}",
    uploadPdfLabel: "Carregar PDF / Foto",
    licenseUploaded: "LICENCA_ENVIADA.PDF",
    summaryServices: "Serviços",
    summaryPlan: "Plano",
    summaryIban: "IBAN",
    trustedPros: "Seus profissionais de confiança.",
    navRequests: "Pedidos",
    navMarket: "Mercado",
    navChat: "Chat",
    navFavs: "Favoritos",
    activePlan: "(Ativo)",
    closedDay: "Fechado",
    paymentValidation: "Necessário para validação. Você não será cobrado hoje.",
    botMessageAgility: "Olá! Sou o assistente virtual. O profissional está dirigindo ou em serviço no momento. Ele já recebeu seu pedido e responderá pessoalmente assim que possível!",
    botMessageData: "Obrigado por nos escolher! Estou finalizando um atendimento. Para agilizar, poderia me enviar fotos do local ou descrever o problema com mais detalhes aqui? Já já eu respondo.",
    botMessageCustomDefault: "Bem-vindo! Estarei com você em breve."
};

const frTranslations: typeof enTranslations = {
    // ... EXISTING KEYS ...
    signIn: "Se connecter",
    welcomeSubtitle: "Bienvenue sur ServiceBid",
    imClient: "Je suis Client",
    imPro: "Je suis Pro",
    myWebsite: "Mon Site Web",
    siteStatus: "Statut du Site",
    online: "EN LIGNE",
    offline: "HORS LIGNE",
    copyLink: "Copier le lien",
    shareWhatsapp: "Partager sur WhatsApp",
    appearance: "Apparence",
    selectTheme: "Choisir un Thème",
    accentColor: "Couleur d'Accent",
    previewSite: "VOIR MON SITE 👁️",
    siteInfo: "Le saviez-vous ?",
    siteInfoDesc: "Le contenu de votre site (Photos, Avis, Bio) est automatiquement synchronisé depuis votre Profil. Pas besoin d'éditer deux fois !",
    themeModern: "Moderne",
    themeClassic: "Classique",
    themeBold: "Audacieux",
    themeMinimal: "Minimal",
    visitExternal: "Ouvrir",
    linkCopied: "Lien Copié !",
    loginWithEmail: "E-mail",
    loginWithPhone: "Téléphone",
    email: "E-mail",
    phoneLabel: "Numéro de téléphone",
    password: "Mot de passe",
    forgotPassword: "Mot de passe oublié ?",
    dontHaveAccount: "Pas de compte ?",
    signUp: "S'inscrire",
    loggedAs: "Connecté en tant que",
    dashboard: "Tableau de Bord",
    profile: "Profil",
    logout: "Déconnexion",
    personalDetails: "Détails Personnels",
    businessDetails: "Détails Entreprise",
    servicesAndScope: "Services & Activité",
    licenseDetails: "Détails Licence",
    financialPlan: "Plan Financier",
    reviewDetails: "Révision",
    fullName: "Nom Complet",
    cnsNumber: "Numéro CNS",
    street: "Rue",
    houseNumber: "Numéro",
    postalCode: "Code Postal",
    locality: "Localité",
    idUpload: "Télécharger Carte ID",
    independant: "Indépendant",
    societe: "Société (S.à r.l.)",
    companyName: "Nom de la Société",
    tvaNumber: "Numéro TVA",
    rcsNumber: "Numéro RCS",
    selectServices: "Sélectionnez vos Services",
    selectServicesDesc: "Choisissez vos catégories d'activité",
    licenseNum: "Numéro de Licence",
    licenseExpiry: "Expiration Licence",
    planSelect: "Sélectionnez votre Plan",
    founderOffer: "OFFRE FONDATEUR",
    premiumPlan: "Plan Premium",
    lifetimeAccess: "Accès à Vie",
    benefitSite: "Site Web Pro + SEO",
    benefitPriority: "Priorité Recherche",
    benefitFees: "0% Commission",
    benefitSupport: "Support Dédié",
    benefitBadge: "Badge Fondateur",
    durationLabel: "Durée :",
    freeForever: "Gratuit à Vie",
    basicPlan: "Plan Basique",
    basicDesc: "Accès standard à la plateforme",
    payoutDetails: "Détails Versement",
    iban: "IBAN",
    accHolder: "Titulaire Compte",
    paymentMethod: "Méthode Paiement",
    expiryDate: "MM/AA",
    cvc: "CVC",
    cardHolder: "Titulaire Carte",
    websiteReady: "Site Web Prêt !",
    websiteDesc: "Votre site professionnel est prêt.",
    visitSite: "Voir Site",
    generatedFor: "Généré pour",
    declaration: "Je déclare que les informations sont correctes.",
    back: "Retour",
    next: "Suivant",
    finish: "Terminer",
    heroTitle: "Trouvez les meilleurs <span class='text-emerald-500'>pros</span> au Luxembourg",
    heroSubtitle: "Devis en quelques minutes pour nettoyage, rénovation, déménagement et plus.",
    searchPlaceholder: "De quoi avez-vous besoin ?",
    trustSecure: "Pros Vérifiés",
    trustStars: "Mieux Notés",
    trustFast: "Devis Rapides",
    popularCategories: "Catégories Populaires",
    exploreServices: "Explorez nos services",
    results: "Résultats",
    noServices: "Aucun service trouvé pour",
    clearSearch: "Effacer recherche",
    proCTA: "Vous êtes Pro ?",
    proCTADesc: "Rejoignez le réseau et développez votre activité.",
    proCTABtn: "S'inscrire comme Pro",
    noCompany: "Pas d'Entreprise ?",
    openCompanyHelpBtn: "On vous aide",
    openCompanyBtn: "Créer Entreprise",
    whatNeed: "De quoi avez-vous besoin ?",
    describeProblem: "Décrivez votre demande",
    whereWhen: "Où & Quand ?",
    defineLocation: "Lieu et horaire",
    photosOptional: "Photos (Optionnel)",
    helpPro: "Aidez les pros à comprendre",
    stepXofY: "Étape {x} sur {y}",
    titleLabel: "Titre",
    titlePlaceholder: "ex: Robinet qui fuit",
    detailsLabel: "Détails",
    detailsPlaceholder: "Décrivez le problème...",
    addressPlaceholder: "Entrez l'adresse",
    whenLabel: "Pour quand ?",
    urgencyAsap: "Dès que possible",
    urgencyThisWeek: "Cette semaine",
    urgencyPlanning: "Planification",
    budgetLabel: "Budget",
    budgetPlaceholder: "Budget estimé",
    budgetHelp: "Aide les pros à chiffrer",
    addPhoto: "Ajouter Photo",
    photoTip: "Les photos aident à obtenir des devis précis",
    requestQuotes: "Demander Devis",
    saveChanges: "Enregistrer",
    myRequests: "Mes Demandes",
    manageRequests: "Gérer vos demandes de service",
    createFirstRequest: "Créer Demande",
    noActiveRequests: "Aucune demande active",
    goToMarket: "Voir le Marché",
    editRequest: "Modifier",
    deleteRequest: "Supprimer",
    monitoringPaused: "En Pause",
    monitoringActive: "En Direct",
    resumeMonitoring: "Reprendre",
    pauseMonitoring: "Pause",
    realTime: "Temps Réel",
    targetBudget: "Budget Cible",
    averageOffer: "Offre Moy.",
    incomingOffers: "Offres Reçues",
    viewPhotos: "Photos",
    viewFullProfile: "Profil Complet",
    acceptOffer: "Accepter",
    budgetFit: "Bon Prix",
    aboveTarget: "Au-dessus",
    selectRequestToView: "Sélectionnez une demande pour voir le marché",
    historyTab: "Historique",
    noRequestsDesc: "Aucun historique disponible",
    financialPerformance: "Tableau de Bord Financier",
    filterToday: "Auj.",
    filterWeek: "7 Derniers Jours",
    filterMonth: "30 Derniers Jours",
    filterYear: "Cette Année",
    totalEarnings: "Revenu Brut",
    jobsCompleted: "Jobs",
    breakdown: "Transactions",
    noJobsPeriod: "Aucune transaction sur cette période",
    messagesTab: "Messages",
    radar: "Radar",
    nearby: "À Proximité",
    offerLabel: "Offre",
    yourOffer: "Votre Offre",
    acceptAndChat: "Accepter & Discuter",
    serviceAgreed: "Service convenu à",
    chatStarted: "Discussion démarrée.",
    msgOnWay: "Je suis en route.",
    msgArrived: "Je suis arrivé.",
    msgStarted: "Service démarré.",
    msgPriceUpdate: "Prix mis à jour à",
    proposalUpdate: "Mise à Jour Proposition",
    offerAccepted: "Offre Acceptée",
    offerDeclined: "Offre Refusée",
    receiptTitle: "Reçu",
    startTime: "Début",
    endTime: "Fin",
    duration: "Durée",
    total: "Total",
    actionOnWay: "En Route",
    actionArrived: "Arrivé",
    actionStart: "Démarrer",
    actionFinish: "Terminer",
    serviceCompleted: "Service Terminé",
    experienceQuestion: "Comment s'est passée votre expérience avec",
    writeReview: "Écrire un avis...",
    submitReview: "Envoyer Avis",
    finishJob: "Générer Facture & Terminer",
    onlineNow: "En ligne",
    typeMessage: "Écrivez un message...",
    leaveNegotiation: "Quitter Négociation ?",
    leaveNegotiationDesc: "Vous avez une négociation active.",
    returnToMarket: "Retour au Marché",
    stayHere: "Rester Ici",
    updateOffer: "Mettre à jour l'offre",
    newPrice: "Nouveau Prix",
    reasonChange: "Raison du changement",
    sendUpdate: "Envoyer Maj",
    confirmChange: "Confirmer Changement",
    confirmChangeDesc: "Acceptez-vous le prix de",
    confirmChangeSuffix: " ?",
    yesConfirm: "Oui, Confirmer",
    cancel: "Annuler",
    personalInfo: "Infos Personnelles",
    companyData: "Données Entreprise",
    addressLogistics: "Adresse & Logistique",
    security: "Sécurité",
    logisticsNote: "Logistique",
    luxNoteDesc: "Info logistique Luxembourg",
    companyDesc: "Gérer les détails de l'entreprise",
    cantEditHelp: "Certains champs sont en lecture seule",
    legalForm: "Forme Juridique",
    govAuth: "Autorisation Gouv",
    banking: "Bancaire",
    manageIdentity: "Gérer Identité",
    languages: "Langues",
    smartAddress: "Adresse Intelligente",
    connectPortfolio: "Connecter Instagram",
    connectPortfolioDesc: "Affichez votre travail directement depuis Instagram",
    connecting: "Connexion...",
    connectBtn: "Connecter",
    autoSync: "Synchro Auto",
    instaConnected: "Instagram Connecté",
    itemsSynced: "éléments synchro",
    disconnect: "Déconnecter",
    noCaption: "Pas de légende",
    postedOn: "Publié le",
    wantService: "Je veux ce service",
    rating: "Note",
    jobs: "Jobs",
    xp: "XP",
    speaks: "Parle",
    serviceLocation: "Lieu du Service",
    openMaps: "Ouvrir Plans",
    bio: "Bio",
    serviceTimeline: "Chronologie Service",
    hireNow: "Engager",
    viewInstaBtn: "Voir Portfolio",
    statusConfirmed: "Confirmé",
    subConfirmed: "Pro planifié",
    statusEnRoute: "En Route",
    subEnRoute: "Pro en chemin",
    statusArrived: "Arrivé",
    subArrived: "Pro sur place",
    statusInProgress: "En Cours",
    subInProgress: "Service en cours",
    statusCompleted: "Terminé",
    subCompleted: "Service fini",
    recording: "Enregistrement",
    clientRole: "Client",
    reliableClient: "Fiable",
    requestsMade: "Demandes",
    paymentRate: "Taux Paiement",
    subscription: "Abonnement & Facturation",
    currentPlan: "Plan Actuel",
    paymentCard: "Carte de Paiement",
    changeCard: "Changer Carte",
    availBalance: "Solde Disponible",
    pendingBalance: "En Attente",
    vatEstimate: "Est. TVA (17%)",
    exportReport: "Rapport Fiscal",
    downloadPdf: "Télécharger PDF",
    invoiceNo: "Facture N°",
    client: "Client",
    service: "Service",
    amountHT: "Montant (HT)",
    amountTTC: "Total (TTC)",
    upgradePro: "Passer Pro",
    upgradeDesc: "Automatisez votre comptabilité avec des factures luxembourgeoises conformes.",
    invBillTo: "Facturé à",
    invDate: "Date Facture",
    invDue: "Échéance",
    invDesc: "Description",
    invQty: "Qté",
    invRate: "Taux",
    invTotal: "Total",
    invSubtotal: "Sous-total (HT)",
    invVatAmt: "Montant TVA",
    invTotalDue: "Total Dû (TTC)",
    invFooter: "Paiement dû sous 14 jours. Merci d'inclure le numéro de facture dans la référence.",
    businessHours: "Horaires d'Ouverture",
    openingTime: "Ouverture",
    closingTime: "Fermeture",
    workingDays: "Jours Ouvrables",
    addToFavorites: "Ajouter aux Favoris",
    removeFromFavorites: "Retirer des Favoris",
    blockContact: "Bloquer l'Entreprise",
    unblockContact: "Débloquer",
    blockedUsers: "Utilisateurs Bloqués",
    noBlockedUsers: "Aucun utilisateur bloqué.",
    favoritesTab: "Favoris",
    noFavorites: "Aucun favori pour l'instant.",
    contactInfo: "Infos Contact",
    onlinePresence: "En Ligne & Social",
    startDate: "De",
    endDate: "À",
    customRange: "Période",
    revenueTrend: "Tendance Revenus",
    averageValue: "Panier Moyen",
    confirmWorkDone: "Le travail est-il fait ?",
    confirmWorkDoneDesc: "Le Pro a marqué le travail comme terminé. Confirmez-vous ?",
    yesFinished: "Oui, Terminé",
    noNotYet: "Non, Pas Encore",
    confirmPayment: "Avez-vous reçu le paiement ?",
    confirmPaymentDesc: "Le client a confirmé. Avez-vous reçu le montant ?",
    yesReceived: "Oui, Reçu",
    quickTags: "Tags Rapides",
    tagPunctual: "Ponctuel",
    tagClean: "Propre",
    tagPro: "Professionnel",
    tagFriendly: "Sympa",
    tagFair: "Prix Juste",
    chatArchived: "Chat Archivé",
    reopenChat: "Rouvrir le Chat",
    waitingClient: "En attente du Client...",
    waitingPayment: "En attente du Paiement...",
    // ADDED KEYS
    liveFeed: "Flux en Direct",
    opportunities: "Opportunités",
    roleLabel: "Rôle :",
    quickAccess: "Accès Rapide (Démo)",
    orLoginManual: "Ou connexion manuelle",
    licenseInfo: "Cette licence est délivrée par le Ministère de l'Économie. Obligatoire pour la plupart des activités au LU.",
    uploadPdf: "Télécharger PDF / Photo",
    attached: "Document Joint",
    newAddress: "Nouvelle Adresse",
    liveMarket: "Marché en Direct",
    instaPortfolio: "Portfolio Instagram",
    jobClosed: "Travail Clôturé et Archivé.",
    invoiceGen: "Facture Générée. En attente de confirmation client.",
    chatReopened: "Discussion Rouverte.",
    // SMART REPLY
    chatSettings: "Paramètres de Chat",
    smartReply: "Réponse Intelligente",
    smartReplyDesc: "Réponse automatique lorsque vous conduisez ou êtes occupé.",
    activationTime: "Activer si pas de réponse dans :",
    immediate: "Immédiat",
    mins5: "5 Minutes",
    mins15: "15 Minutes",
    botPersonality: "Personnalité du Bot",
    agilityMode: "Agilité (Focus Vitesse)",
    agilityDesc: "Informe que vous conduisez et répondrez bientôt.",
    dataMode: "Collecte de Données (Recommandé)",
    dataDesc: "Demande des photos et détails pour accélérer le devis.",
    customMode: "Message Personnalisé",
    customDesc: "Écrivez votre propre message d'accueil.",
    botMsgFooter: "Réponse auto - Pro notifié.",
    // MISSING KEYS TRANSLATION
    enableAutoReply: "Activer les réponses automatiques",
    preview: "Aperçu",
    yourMessage: "Votre Message",
    financialErp: "Financier (ERP)",
    scanningJobs: "Recherche de jobs...",
    upgradeNow: "Mettre à niveau maintenant",
    upgradeBtn: "Mettre à niveau",
    stepIndicator: "Étape {step} sur {total}",
    uploadPdfLabel: "Télécharger PDF / Photo",
    licenseUploaded: "LICENCE_TELECHARGEE.PDF",
    summaryServices: "Services",
    summaryPlan: "Plan",
    summaryIban: "IBAN",
    trustedPros: "Vos professionnels de confiance.",
    navRequests: "Demandes",
    navMarket: "Marché",
    navChat: "Chat",
    navFavs: "Favoris",
    activePlan: "(Actif)",
    closedDay: "Fermé",
    paymentValidation: "Requis pour la validation. Vous ne serez pas débité aujourd'hui.",
    botMessageAgility: "Bonjour! Je suis l'assistant virtuel. Le professionnel conduit ou travaille actuellement. Il a bien reçu votre demande et vous répondra personnellement dès que possible!",
    botMessageData: "Merci de nous avoir choisis! Je termine un travail en ce moment. Pour gagner du temps, pourriez-vous envoyer des photos ou décrire le problème plus en détail ici? Je vous réponds sous peu.",
    botMessageCustomDefault: "Bienvenue! Je serai avec vous sous peu."
};

const translations = {
  EN: enTranslations,
  PT: ptTranslations,
  FR: frTranslations,
  DE: enTranslations, // Fallback to EN for now, but ensures DE key exists
  LB: frTranslations
};

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: typeof enTranslations;
  tCategory: (catId: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('FR');

  const t = translations[language];

  // Helper to translate categories since they are dynamic IDs
  const tCategory = (catId: string) => {
    return catId; 
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tCategory }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
