
import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'EN' | 'FR' | 'DE' | 'LB' | 'PT';

export const LANGUAGES_LIST: { code: Language; label: string; flag: string }[] = [
  { code: 'FR', label: 'Français', flag: '🇫🇷' },
  { code: 'PT', label: 'Português', flag: '🇧🇷' },
  { code: 'EN', label: 'English', flag: '🇬🇧' },
  { code: 'DE', label: 'Deutsch', flag: '🇩🇪' },
  { code: 'LB', label: 'Lëtzebuergesch', flag: '🇱🇺' },
];

// --- ENGLISH (Base) ---
const enTranslations = {
    // AUTH & GENERAL
    signIn: "Sign In",
    welcomeSubtitle: "Welcome back to ServiceBid",
    imClient: "I'm a Client",
    imPro: "I'm a Pro",
    myWebsite: "My Website",
    siteStatus: "Site Status",
    online: "ONLINE",
    offline: "OFFLINE",
    copyLink: "Copy Link",
    shareWhatsapp: "Share on WhatsApp",
    appearance: "Appearance",
    selectTheme: "Select Theme",
    accentColor: "Accent Color",
    previewSite: "PREVIEW MY SITE",
    siteInfo: "Did you know?",
    siteInfoDesc: "Your site content (Photos, Reviews, Bio) is automatically synced from your Profile.",
    themeModern: "Modern",
    themeClassic: "Classic",
    themeBold: "Bold",
    themeMinimal: "Minimal",
    visitExternal: "Open in Browser",
    linkCopied: "Link Copied!",
    loginWithEmail: "Email",
    loginWithPhone: "Phone",
    email: "Email",
    phoneLabel: "Phone Number",
    password: "Password",
    forgotPassword: "Forgot Password?",
    dontHaveAccount: "Don't have an account?",
    signUp: "Sign Up",
    loggedAs: "Logged in as",
    dashboard: "Dashboard",
    profile: "Profile",
    logout: "Logout",
    
    // ONBOARDING STEPS
    personalDetails: "Personal Details",
    businessDetails: "Business Details",
    servicesAndScope: "Services & Scope",
    licenseDetails: "License Details",
    financialPlan: "Financial Plan",
    reviewDetails: "Review Details",
    fullName: "Full Name",
    cnsNumber: "CNS Number",
    street: "Street",
    houseNumber: "Number",
    postalCode: "Postal Code",
    locality: "Locality",
    idUpload: "Upload ID Card",
    independant: "Independente",
    societe: "Company (S.à r.l.)",
    companyName: "Company Name",
    tvaNumber: "VAT Number",
    rcsNumber: "RCS Number",
    selectServices: "Select your Services",
    selectServicesDesc: "Choose the categories you work in",
    licenseNum: "License Number",
    licenseExpiry: "License Expiry",
    
    // NEW ONBOARDING KEYS (PLAN SELECTION)
    planSelect: "Select your Plan",
    founderOffer: "Founder Offer",
    premiumPlan: "Premium Plan",
    lifetimeAccess: "Lifetime Access",
    benefitSite: "Pro Website + SEO",
    benefitPriority: "Search Priority",
    benefitFees: "0% Commission Fees",
    benefitSupport: "Dedicated Support",
    benefitBadge: "Founding Member Badge",
    durationLabel: "Duration:",
    freeForever: "Free Forever",
    basicPlan: "Basic Plan",
    basicDesc: "Standard platform access",
    payoutDetails: "Payout Details",
    iban: "IBAN",
    accHolder: "Account Holder",
    paymentMethod: "Payment Method",
    expiryDate: "MM/YY",
    cvc: "CVC",
    cardHolder: "Card Holder",
    websiteReady: "Website Ready!",
    websiteDesc: "Your professional site is ready.",
    visitSite: "Visit Site",
    generatedFor: "Generated for",
    declaration: "I declare the information is correct.",
    paymentValidation: "Required for verification. No charge today.",
    
    // NAVIGATION
    back: "Back",
    next: "Next",
    finish: "Finish",
    
    // LANDING
    heroTitle: "Find the best <span class='text-emerald-500'>pros</span> in Luxembourg",
    heroSubtitle: "Get quotes in minutes for cleaning, renovation, moving and more.",
    searchPlaceholder: "What do you need help with?",
    trustSecure: "Verified Pros",
    trustStars: "Top Rated",
    trustFast: "Quick Quotes",
    popularCategories: "Popular Professionals", // UPDATED
    viewAllServices: "View all services", // NEW
    allServicesTitle: "Find the ideal specialist", // NEW
    exploreServices: "Explore our services",
    results: "Results",
    noServices: "No services found for",
    clearSearch: "Clear search",
    proCTA: "Are you a Pro?",
    proCTADesc: "Join the network and grow your business.",
    proCTABtn: "Register as Pro",
    noCompany: "No Company?",
    openCompanyHelpBtn: "We help you start",
    openCompanyBtn: "Start Company",
    
    // SECTORS (NEW EXPANDED)
    sectorHome: "Home & Construction",
    sectorAuto: "Auto & Transport",
    sectorTech: "Tech & Digital",
    sectorBusiness: "Business & Legal",
    sectorEvents: "Events & Party",
    sectorLifestyle: "Lifestyle & Care",
    sectorEducation: "Education & Music",
    
    // WIZARD & REQUESTS
    whatNeed: "What do you need?",
    describeProblem: "Describe your request",
    whereWhen: "Where & When?",
    defineLocation: "Location and timing",
    photosOptional: "Photos (Optional)",
    helpPro: "Help pros understand better",
    stepXofY: "Step {x} of {y}",
    titleLabel: "Title",
    titlePlaceholder: "e.g. Leaking faucet",
    detailsLabel: "Details",
    detailsPlaceholder: "Describe the issue...",
    addressPlaceholder: "Enter address",
    whenLabel: "When?",
    urgencyAsap: "As soon as possible",
    urgencyThisWeek: "This week",
    urgencyPlanning: "Planning phase",
    budgetLabel: "Budget",
    budgetPlaceholder: "Estimated budget",
    budgetHelp: "This helps pros give better quotes",
    addPhoto: "Add Photo",
    photoTip: "Photos help get more accurate quotes",
    requestQuotes: "Request Quotes",
    saveChanges: "Save Changes",
    myRequests: "My Requests",
    manageRequests: "Manage your service requests",
    createFirstRequest: "Create Request",
    noActiveRequests: "No active requests",
    goToMarket: "Go to Market",
    editRequest: "Edit",
    deleteRequest: "Delete",
    
    // DASHBOARD & ANALYTICS
    historyTab: "History",
    noRequestsDesc: "No history available",
    financialPerformance: "Financial Dashboard",
    filterToday: "Today",
    filterWeek: "Last 7 Days",
    filterMonth: "Last 30 Days",
    filterYear: "This Year",
    totalEarnings: "Gross Revenue",
    jobsCompleted: "Jobs",
    breakdown: "Transactions",
    noJobsPeriod: "No transactions in this period",
    messagesTab: "Messages",
    radar: "Radar",
    nearby: "Nearby",
    offerLabel: "Offer",
    yourOffer: "Your Offer",
    acceptAndChat: "Accept & Chat",
    availBalance: "Available Balance",
    pendingBalance: "Pending",
    vatEstimate: "VAT Estimate (17%)",
    exportReport: "Export Fiscal Report",
    downloadPdf: "Download PDF",
    invoiceNo: "Invoice N°",
    client: "Client",
    service: "Service",
    amountHT: "Net (HT)",
    amountTTC: "Total (TTC)",
    revenueTrend: "Revenue Trend",
    averageValue: "Avg Ticket",
    
    // NEW FINANCIAL KEYS
    addExternalService: "Add External Service",
    externalServiceDef: "External Service",
    selectCategory: "Select Category",
    addTransaction: "Add Transaction",
    methodCash: "Cash",
    methodCard: "Card",
    methodTransfer: "Bank Transfer",
    filterAll: "All",
    methodColumn: "Method",
    actionColumn: "Action",
    provisionTax: "Provision for future tax payment",
    monthlyAgg: "Monthly Aggregation",
    dailyBreak: "Daily Breakdown",
    expandRange: "Try selecting a wider date range.",
    upgradeTitle: "Upgrade to PRO",
    upgradeText: "Unlock full financial dashboard and export tools.",
    
    // CHAT & WORKFLOW
    serviceAgreed: "Service agreed at",
    chatStarted: "Chat started.",
    msgOnWay: "I am on my way.",
    msgArrived: "I have arrived.",
    msgStarted: "Service started.",
    msgPriceUpdate: "Price updated to",
    proposalUpdate: "Proposal Update",
    offerAccepted: "Offer Accepted",
    offerDeclined: "Offer Declined",
    acceptOffer: "Accept Offer",
    receiptTitle: "Receipt",
    startTime: "Start Time",
    endTime: "End Time",
    duration: "Duration",
    total: "Total",
    actionOnWay: "On My Way",
    actionArrived: "Arrived",
    actionStart: "Start Job",
    actionFinish: "Finish Job",
    serviceCompleted: "Service Completed",
    experienceQuestion: "How was your experience with",
    writeReview: "Write a review...",
    submitReview: "Submit Review",
    finishJob: "Generate Invoice & Finish",
    onlineNow: "Online",
    typeMessage: "Type a message...",
    leaveNegotiation: "Leave Negotiation?",
    leaveNegotiationDesc: "You have an active negotiation.",
    returnToMarket: "Return to Market",
    stayHere: "Stay Here",
    updateOffer: "Update Offer",
    newPrice: "New Price",
    reasonChange: "Reason for change",
    sendUpdate: "Send Update",
    confirmChange: "Confirm Change",
    confirmChangeDesc: "Do you accept the price of",
    confirmChangeSuffix: "?",
    yesConfirm: "Yes, Confirm",
    cancel: "Cancel",
    confirmWorkDone: "Is the job done?",
    confirmWorkDoneDesc: "Pro has marked the job as finished. Please confirm.",
    yesFinished: "Yes, Finished",
    noNotYet: "No, Not Yet",
    confirmPayment: "Did you receive payment?",
    confirmPaymentDesc: "Client has confirmed. Did you get paid?",
    yesReceived: "Yes, Payment Received",
    chatArchived: "Chat Archived",
    reopenChat: "Reopen Chat",
    waitingClient: "Waiting for Client...",
    waitingPayment: "Waiting for Payment...",
    liveFeed: "Live Feed",
    opportunities: "Opportunities",
    liveMarket: "Live Market",
    jobClosed: "Job Closed & Archived.",
    invoiceGen: "Invoice Generated. Waiting for client confirmation.",
    chatReopened: "Chat Reopened.",
    statusConfirmed: "Service Confirmed",
    subConfirmed: "Pro has accepted the request",
    statusEnRoute: "On the Way",
    subEnRoute: "Pro is traveling to location",
    statusArrived: "Arrived",
    subArrived: "Pro is at the location",
    statusInProgress: "In Progress",
    subInProgress: "Service is being performed",
    statusCompleted: "Completed",
    subCompleted: "Service finished",
    
    // PROFILE & SETTINGS
    personalInfo: "Personal Info",
    companyData: "Company Data",
    addressLogistics: "Address & Logistics",
    security: "Security",
    logisticsNote: "Logistics",
    luxNoteDesc: "Luxembourg logistics info",
    companyDesc: "Manage your company details",
    cantEditHelp: "Some fields are read-only",
    legalForm: "Legal Form",
    govAuth: "Gov Authorization",
    banking: "Banking",
    manageIdentity: "Manage Identity",
    languages: "Languages",
    smartAddress: "Smart Address",
    connectPortfolio: "Connect Instagram",
    connectPortfolioDesc: "Showcase your work directly from Instagram",
    connecting: "Connecting...",
    connectBtn: "Connect",
    autoSync: "Auto Sync",
    instaConnected: "Instagram Connected",
    itemsSynced: "items synced",
    disconnect: "Disconnect",
    noCaption: "No caption",
    postedOn: "Posted on",
    wantService: "I want this service",
    rating: "Rating",
    jobs: "Jobs",
    xp: "XP",
    speaks: "Speaks",
    serviceLocation: "Service Location",
    openMaps: "Open Maps",
    bio: "Bio",
    serviceTimeline: "Service Timeline",
    hireNow: "Hire Now",
    viewInstaBtn: "View Portfolio",
    recording: "Recording",
    clientRole: "Client",
    reliableClient: "Reliable",
    requestsMade: "Requests",
    paymentRate: "Payment Rate",
    subscription: "Subscription & Billing",
    currentPlan: "Current Plan",
    paymentCard: "Payment Card",
    changeCard: "Change Card",
    upgradePro: "Upgrade to PRO",
    upgradeDesc: "Automate your accounting with compliant Luxembourgish invoices.",
    invBillTo: "Bill To",
    invDate: "Invoice Date",
    invDue: "Due Date",
    invDesc: "Description",
    invQty: "Qty",
    invRate: "Rate",
    invTotal: "Total",
    invSubtotal: "Subtotal (HT)",
    invVatAmt: "VAT Amount",
    invTotalDue: "Total Due (TTC)",
    invFooter: "Payment due within 14 days.",
    businessHours: "Business Hours",
    openingTime: "Opening Time",
    closingTime: "Closing Time",
    workingDays: "Working Days",
    addToFavorites: "Add to Favorites",
    removeFromFavorites: "Remove Favorite",
    blockContact: "Block Business",
    unblockContact: "Unblock",
    blockedUsers: "Blocked Users",
    noBlockedUsers: "No blocked users.",
    favoritesTab: "Favorites",
    noFavorites: "No favorites yet.",
    contactInfo: "Contact Info",
    onlinePresence: "Online & Social",
    startDate: "From",
    endDate: "To",
    customRange: "Custom Range",
    roleLabel: "Role:",
    quickAccess: "Quick Access (Demo)",
    orLoginManual: "Or login manual",
    licenseInfo: "This license is issued by the Ministry of the Economy.",
    uploadPdfLabel: "Upload PDF / Photo",
    attached: "Document Attached",
    instaPortfolio: "Instagram Portfolio",
    summaryServices: "Services",
    summaryPlan: "Plan",
    summaryIban: "IBAN",
    activePlan: "(Active)",
    closedDay: "Closed",
    
    // SMART REPLY
    chatSettings: "Chat Settings",
    smartReply: "Smart Reply",
    smartReplyDesc: "Auto-reply when you are busy or driving.",
    activationTime: "Activate if no reply in:",
    immediate: "Immediately",
    mins5: "5 Minutes",
    mins15: "15 Minutes",
    botPersonality: "Bot Personality",
    agilityMode: "Agility (Focus on Speed)",
    agilityDesc: "Inform that you are driving and will reply soon.",
    dataMode: "Data Collection (Recommended)",
    dataDesc: "Ask for photos and details to speed up the quote.",
    customMode: "Custom Message",
    customDesc: "Write your own welcome message.",
    botMsgFooter: "Automated reply - Pro notified.",
    enableAutoReply: "Enable automated responses",
    preview: "Preview",
    yourMessage: "Your Message",
    botMessageAgility: "Hello! I'm the virtual assistant. The professional is currently driving or working. He has received your request and will reply personally ASAP!",
    botMessageData: "Thanks for choosing us! I'm finishing a job right now. To speed things up, could you send photos or describe the issue in more detail here? I'll reply shortly.",
    botMessageCustomDefault: "Welcome! I will be with you shortly.",
    
    // MISC
    financialErp: "Financial (ERP)",
    scanningJobs: "Scanning for jobs...",
    upgradeNow: "Upgrade Now",
    upgradeBtn: "Upgrade",
    stepIndicator: "Step {step} of {total}",
    licenseUploaded: "LICENSE_UPLOADED.PDF",
    
    // TAGS
    tagPunctual: "Punctual",
    tagClean: "Clean Work",
    tagPro: "Professional",
    tagFriendly: "Friendly",
    tagFair: "Fair Price",
};

// --- FRENCH (Default) ---
const frTranslations: typeof enTranslations = {
    ...enTranslations,
    signIn: "Se connecter",
    welcomeSubtitle: "Bienvenue sur ServiceBid",
    imClient: "Je suis Client",
    imPro: "Je suis Pro",
    myWebsite: "Mon Site Web",
    siteStatus: "Statut du Site",
    online: "EN LIGNE",
    offline: "HORS LIGNE",
    copyLink: "Copier le lien",
    shareWhatsapp: "Partager sur WhatsApp",
    appearance: "Apparence",
    selectTheme: "Choisir un Thème",
    accentColor: "Couleur d'Accent",
    previewSite: "VOIR MON SITE 👁️",
    siteInfo: "Le saviez-vous ?",
    siteInfoDesc: "Le contenu de votre site est automatiquement synchronisé depuis votre Profil.",
    themeModern: "Moderne",
    themeClassic: "Classique",
    themeBold: "Audacieux",
    themeMinimal: "Minimal",
    visitExternal: "Ouvrir",
    linkCopied: "Lien Copié !",
    loginWithEmail: "E-mail",
    loginWithPhone: "Téléphone",
    email: "E-mail",
    phoneLabel: "Numéro de téléphone",
    password: "Mot de passe",
    forgotPassword: "Mot de passe oublié ?",
    dontHaveAccount: "Pas de compte ?",
    signUp: "S'inscrire",
    loggedAs: "Connecté en tant que",
    dashboard: "Tableau de Bord",
    profile: "Profil",
    logout: "Déconnexion",
    
    personalDetails: "Détails Personnels",
    businessDetails: "Détails Entreprise",
    servicesAndScope: "Services & Activité",
    licenseDetails: "Détails Licence",
    financialPlan: "Plan Financier",
    reviewDetails: "Révision",
    fullName: "Nom Complet",
    cnsNumber: "Numéro CNS",
    street: "Rue",
    houseNumber: "Numéro",
    postalCode: "Code Postal",
    locality: "Localité",
    idUpload: "Télécharger Carte ID",
    independant: "Indépendant",
    societe: "Société (S.à r.l.)",
    companyName: "Nom de la Société",
    tvaNumber: "Numéro TVA",
    rcsNumber: "Numéro RCS",
    selectServices: "Sélectionnez vos Services",
    selectServicesDesc: "Choisissez vos catégories d'activité",
    licenseNum: "Numéro de Licence",
    licenseExpiry: "Expiration Licence",
    
    planSelect: "Sélectionnez votre Plan",
    founderOffer: "OFFRE FONDATEUR",
    premiumPlan: "Plan Premium",
    lifetimeAccess: "Accès à Vie",
    benefitSite: "Site Web Pro + SEO",
    benefitPriority: "Priorité Recherche",
    benefitFees: "0% Commission",
    benefitSupport: "Support Dédié",
    benefitBadge: "Badge Fondateur",
    durationLabel: "Durée :",
    freeForever: "Gratuit à Vie",
    basicPlan: "Plan Basique",
    basicDesc: "Accès standard à la plateforme",
    payoutDetails: "Détails Versement",
    iban: "IBAN",
    accHolder: "Titulaire Compte",
    paymentMethod: "Méthode Paiement",
    expiryDate: "MM/AA",
    cvc: "CVC",
    cardHolder: "Titulaire Carte",
    websiteReady: "Site Web Prêt !",
    websiteDesc: "Votre site professionnel est prêt.",
    visitSite: "Voir Site",
    generatedFor: "Généré pour",
    declaration: "Je déclare que les informations sont correctes.",
    paymentValidation: "Requis pour la validation. Pas de débit aujourd'hui.",
    
    back: "Retour",
    next: "Suivant",
    finish: "Terminer",
    
    heroTitle: "Trouvez les meilleurs <span class='text-emerald-500'>pros</span> au Luxembourg",
    heroSubtitle: "Devis en quelques minutes pour nettoyage, rénovation, déménagement et plus.",
    searchPlaceholder: "De quoi avez-vous besoin ?",
    trustSecure: "Pros Vérifiés",
    trustStars: "Mieux Notés",
    trustFast: "Devis Rapides",
    popularCategories: "Professionnels Populaires", // UPDATED
    viewAllServices: "Voir tous les services", // NEW
    allServicesTitle: "Trouvez le spécialiste idéal", // NEW
    exploreServices: "Explorez nos services",
    results: "Résultats",
    noServices: "Aucun service trouvé pour",
    clearSearch: "Effacer recherche",
    proCTA: "Vous êtes Pro ?",
    proCTADesc: "Rejoignez le réseau et développez votre activité.",
    proCTABtn: "S'inscrire comme Pro",
    noCompany: "Pas d'Entreprise ?",
    openCompanyHelpBtn: "On vous aide",
    openCompanyBtn: "Créer Entreprise",
    
    // SECTORS
    sectorHome: "Maison & Bâtiment",
    sectorAuto: "Auto & Transport",
    sectorTech: "Tech & Digital",
    sectorBusiness: "Affaires & Juridique",
    sectorEvents: "Événementiel",
    sectorLifestyle: "Lifestyle & Soins",
    sectorEducation: "Éducation & Cours",

    whatNeed: "De quoi avez-vous besoin ?",
    describeProblem: "Décrivez votre demande",
    whereWhen: "Où & Quand ?",
    defineLocation: "Lieu et horaire",
    photosOptional: "Photos (Optionnel)",
    helpPro: "Aidez les pros à comprendre",
    stepXofY: "Étape {x} sur {y}",
    titleLabel: "Titre",
    titlePlaceholder: "ex: Robinet qui fuit",
    detailsLabel: "Détails",
    detailsPlaceholder: "Décrivez le problème...",
    addressPlaceholder: "Entrez l'adresse",
    whenLabel: "Pour quand ?",
    urgencyAsap: "Dès que possible",
    urgencyThisWeek: "Cette semaine",
    urgencyPlanning: "Planification",
    budgetLabel: "Budget",
    budgetPlaceholder: "Budget estimé",
    budgetHelp: "Aide les pros à chiffrer",
    addPhoto: "Ajouter Photo",
    photoTip: "Les photos aident à obtenir des devis précis",
    requestQuotes: "Demander Devis",
    saveChanges: "Enregistrer",
    myRequests: "Mes Demandes",
    manageRequests: "Gérer vos demandes de service",
    createFirstRequest: "Créer Demande",
    noActiveRequests: "Aucune demande active",
    goToMarket: "Voir le Marché",
    editRequest: "Modifier",
    deleteRequest: "Supprimer",
    
    historyTab: "Historique",
    noRequestsDesc: "Aucun historique disponible",
    financialPerformance: "Tableau de Bord Financier",
    filterToday: "Auj.",
    filterWeek: "7 Derniers Jours",
    filterMonth: "30 Derniers Jours",
    filterYear: "Cette Année",
    totalEarnings: "Revenu Brut",
    jobsCompleted: "Jobs",
    breakdown: "Transactions",
    noJobsPeriod: "Aucune transaction sur cette période",
    messagesTab: "Messages",
    radar: "Radar",
    nearby: "À Proximité",
    offerLabel: "Offre",
    yourOffer: "Votre Offre",
    acceptAndChat: "Accepter & Discuter",
    availBalance: "Solde Disponible",
    pendingBalance: "En Attente",
    vatEstimate: "Est. TVA (17%)",
    exportReport: "Rapport Fiscal",
    downloadPdf: "Télécharger PDF",
    invoiceNo: "Facture N°",
    client: "Client",
    service: "Service",
    amountHT: "Montant (HT)",
    amountTTC: "Total (TTC)",
    revenueTrend: "Tendance Revenus",
    averageValue: "Panier Moyen",
    
    // NEW FINANCIAL KEYS
    addExternalService: "Ajouter Service Externe",
    externalServiceDef: "Service Externe",
    selectCategory: "Choisir Catégorie",
    addTransaction: "Ajouter Transaction",
    methodCash: "Espèces",
    methodCard: "Carte",
    methodTransfer: "Virement",
    filterAll: "Tous",
    methodColumn: "Méthode",
    actionColumn: "Action",
    provisionTax: "Provision pour impôts futurs",
    monthlyAgg: "Agrégation Mensuelle",
    dailyBreak: "Détail Journalier",
    expandRange: "Essayez une plage de dates plus large.",
    upgradeTitle: "Passer Pro",
    upgradeText: "Débloquez le tableau de bord financier complet.",

    serviceAgreed: "Service convenu à",
    chatStarted: "Discussion démarrée.",
    msgOnWay: "Je suis en route.",
    msgArrived: "Je suis arrivé.",
    msgStarted: "Service démarré.",
    msgPriceUpdate: "Prix mis à jour à",
    proposalUpdate: "Mise à Jour Proposition",
    offerAccepted: "Offre Acceptée",
    offerDeclined: "Offre Refusée",
    acceptOffer: "Accepter l'offre",
    receiptTitle: "Reçu",
    startTime: "Début",
    endTime: "Fin",
    duration: "Durée",
    total: "Total",
    actionOnWay: "En Route",
    actionArrived: "Arrivé",
    actionStart: "Démarrer",
    actionFinish: "Terminer",
    serviceCompleted: "Service Terminé",
    experienceQuestion: "Comment s'est passée votre expérience avec",
    writeReview: "Écrire un avis...",
    submitReview: "Envoyer Avis",
    finishJob: "Générer Facture & Terminer",
    onlineNow: "En ligne",
    typeMessage: "Écrivez un message...",
    leaveNegotiation: "Quitter Négociation ?",
    leaveNegotiationDesc: "Vous avez une négociation active.",
    returnToMarket: "Retour au Marché",
    stayHere: "Rester Ici",
    updateOffer: "Mettre à jour l'offre",
    newPrice: "Nouveau Prix",
    reasonChange: "Raison du changement",
    sendUpdate: "Envoyer Maj",
    confirmChange: "Confirmer Changement",
    confirmChangeDesc: "Acceptez-vous le prix de",
    confirmChangeSuffix: " ?",
    yesConfirm: "Oui, Confirmer",
    cancel: "Annuler",
    confirmWorkDone: "Le travail est-il fait ?",
    confirmWorkDoneDesc: "Le Pro a marqué le travail comme terminé. Confirmez-vous ?",
    yesFinished: "Oui, Terminé",
    noNotYet: "Non, Pas Encore",
    confirmPayment: "Avez-vous reçu le paiement ?",
    confirmPaymentDesc: "Le client a confirmé. Avez-vous reçu le montant ?",
    yesReceived: "Oui, Reçu",
    chatArchived: "Chat Archivé",
    reopenChat: "Rouvrir le Chat",
    waitingClient: "En attente du Client...",
    waitingPayment: "En attente du Paiement...",
    liveFeed: "Flux en Direct",
    opportunities: "Opportunités",
    liveMarket: "Marché en Direct",
    jobClosed: "Travail Clôturé et Archivé.",
    invoiceGen: "Facture Générée. En attente de confirmation client.",
    chatReopened: "Discussion Rouverte.",
    statusConfirmed: "Service Confirmé",
    subConfirmed: "Le Pro a accepté la demande",
    statusEnRoute: "En Route",
    subEnRoute: "Le Pro se déplace vers le lieu",
    statusArrived: "Arrivé",
    subArrived: "Le Pro est sur place",
    statusInProgress: "En Cours",
    subInProgress: "Service en cours d'exécution",
    statusCompleted: "Terminé",
    subCompleted: "Service terminé",
    
    personalInfo: "Infos Personnelles",
    companyData: "Données Entreprise",
    addressLogistics: "Adresse & Logistique",
    security: "Sécurité",
    logisticsNote: "Logistique",
    luxNoteDesc: "Info logistique Luxembourg",
    companyDesc: "Gérer les détails de l'entreprise",
    cantEditHelp: "Certains champs sont en lecture seule",
    legalForm: "Forme Juridique",
    govAuth: "Autorisation Gouv",
    banking: "Bancaire",
    manageIdentity: "Gérer Identité",
    languages: "Langues",
    smartAddress: "Adresse Intelligente",
    connectPortfolio: "Connecter Instagram",
    connectPortfolioDesc: "Affichez votre travail directement depuis Instagram",
    connecting: "Connexion...",
    connectBtn: "Connecter",
    autoSync: "Synchro Auto",
    instaConnected: "Instagram Connecté",
    itemsSynced: "éléments synchro",
    disconnect: "Déconnecter",
    noCaption: "Pas de légende",
    postedOn: "Publié le",
    wantService: "Je veux ce service",
    rating: "Note",
    jobs: "Jobs",
    xp: "XP",
    speaks: "Parle",
    serviceLocation: "Lieu du Service",
    openMaps: "Ouvrir Plans",
    bio: "Bio",
    serviceTimeline: "Chronologie Service",
    hireNow: "Engager",
    viewInstaBtn: "Voir Portfolio",
    recording: "Enregistrement",
    clientRole: "Client",
    reliableClient: "Fiable",
    requestsMade: "Demandes",
    paymentRate: "Taux Paiement",
    subscription: "Abonnement & Facturation",
    currentPlan: "Plan Actuel",
    paymentCard: "Carte de Paiement",
    changeCard: "Changer Carte",
    upgradePro: "Passer Pro",
    upgradeDesc: "Automatisez votre comptabilité avec des factures luxembourgeoises conformes.",
    invBillTo: "Facturé à",
    invDate: "Date Facture",
    invDue: "Échéance",
    invDesc: "Description",
    invQty: "Qté",
    invRate: "Taux",
    invTotal: "Total",
    invSubtotal: "Sous-total (HT)",
    invVatAmt: "Montant TVA",
    invTotalDue: "Total Dû (TTC)",
    invFooter: "Paiement dû sous 14 jours.",
    businessHours: "Horaires d'Ouverture",
    openingTime: "Ouverture",
    closingTime: "Fermeture",
    workingDays: "Jours Ouvrables",
    addToFavorites: "Ajouter aux Favoris",
    removeFromFavorites: "Retirer des Favoris",
    blockContact: "Bloquer l'Entreprise",
    unblockContact: "Débloquer",
    blockedUsers: "Utilisateurs Bloqués",
    noBlockedUsers: "Aucun utilisateur bloqué.",
    favoritesTab: "Favoris",
    noFavorites: "Aucun favori pour l'instant.",
    contactInfo: "Infos Contact",
    onlinePresence: "En Ligne & Social",
    startDate: "De",
    endDate: "À",
    customRange: "Période",
    roleLabel: "Rôle :",
    quickAccess: "Accès Rapide (Démo)",
    orLoginManual: "Ou connexion manuelle",
    licenseInfo: "Cette licence est délivrée par le Ministère de l'Économie.",
    uploadPdfLabel: "Télécharger PDF / Photo",
    attached: "Document Joint",
    instaPortfolio: "Portfolio Instagram",
    summaryServices: "Services",
    summaryPlan: "Plan",
    summaryIban: "IBAN",
    activePlan: "(Actif)",
    closedDay: "Fermé",
    
    chatSettings: "Paramètres de Chat",
    smartReply: "Réponse Intelligente",
    smartReplyDesc: "Réponse automatique lorsque vous conduisez ou êtes occupé.",
    activationTime: "Activer si pas de réponse dans :",
    immediate: "Immédiat",
    mins5: "5 Minutes",
    mins15: "15 Minutes",
    botPersonality: "Personnalité du Bot",
    agilityMode: "Agilité (Focus Vitesse)",
    agilityDesc: "Informe que vous conduisez et répondrez bientôt.",
    dataMode: "Collecte de Données (Recommandé)",
    dataDesc: "Demande des photos et détails pour accélérer le devis.",
    customMode: "Message Personnalisé",
    customDesc: "Écrivez votre propre message d'accueil.",
    botMsgFooter: "Réponse auto - Pro notifié.",
    enableAutoReply: "Activer les réponses automatiques",
    preview: "Aperçu",
    yourMessage: "Votre Message",
    botMessageAgility: "Bonjour! Je suis l'assistant virtuel. Le professionnel conduit ou travaille actuellement. Il a bien reçu votre demande et vous répondra personnellement dès que possible!",
    botMessageData: "Merci de nous avoir choisis! Je termine un travail en ce moment. Pour gagner du temps, pourriez-vous envoyer des photos ou décrire le problème plus en détail ici? Je vous réponds sous peu.",
    botMessageCustomDefault: "Bienvenue! Je serai avec vous sous peu.",
    
    financialErp: "Financier (ERP)",
    scanningJobs: "Recherche de jobs...",
    upgradeNow: "Mettre à niveau maintenant",
    upgradeBtn: "Mettre à niveau",
    stepIndicator: "Étape {step} sur {total}",
    licenseUploaded: "LICENCE_TELECHARGEE.PDF",
    
    tagPunctual: "Ponctuel",
    tagClean: "Propre",
    tagPro: "Professionnel",
    tagFriendly: "Sympa",
    tagFair: "Prix Juste",
};

// --- PORTUGUESE (Brazil) ---
const ptTranslations: typeof enTranslations = {
    ...enTranslations,
    signIn: "Entrar",
    welcomeSubtitle: "Bem-vindo de volta ao ServiceBid",
    imClient: "Sou Cliente",
    imPro: "Sou Profissional",
    myWebsite: "Meu Site",
    siteStatus: "Status do Site",
    online: "ONLINE",
    offline: "OFFLINE",
    copyLink: "Copiar Link",
    shareWhatsapp: "Enviar no WhatsApp",
    appearance: "Aparência",
    selectTheme: "Escolher Tema",
    accentColor: "Cor de Destaque",
    previewSite: "VISUALIZAR MEU SITE 👁️",
    siteInfo: "Você sabia?",
    siteInfoDesc: "O conteúdo do seu site (Fotos, Textos, Contato) é puxado automaticamente do seu Perfil.",
    themeModern: "Moderno",
    themeClassic: "Clássico",
    themeBold: "Negrito",
    themeMinimal: "Minimalista",
    visitExternal: "Abrir no Navegador",
    linkCopied: "Link Copiado!",
    loginWithEmail: "E-mail",
    loginWithPhone: "Celular",
    email: "E-mail",
    phoneLabel: "Número de Celular",
    password: "Senha",
    forgotPassword: "Esqueceu a senha?",
    dontHaveAccount: "Não tem uma conta?",
    signUp: "Cadastre-se",
    loggedAs: "Logado como",
    dashboard: "Painel",
    profile: "Perfil",
    logout: "Sair",
    
    personalDetails: "Dados Pessoais",
    businessDetails: "Dados da Empresa",
    servicesAndScope: "Atuação e Serviços",
    licenseDetails: "Licença",
    financialPlan: "Plano Financeiro",
    reviewDetails: "Revisão",
    fullName: "Nome Completo",
    cnsNumber: "Número CNS",
    street: "Rua",
    houseNumber: "Número",
    postalCode: "Código Postal",
    locality: "Localidade",
    idUpload: "Enviar Documento",
    independant: "Independente",
    societe: "Sociedade (S.à r.l.)",
    companyName: "Nome da Empresa",
    tvaNumber: "Número IVA",
    rcsNumber: "Número RCS",
    selectServices: "Selecione seus Serviços",
    selectServicesDesc: "Escolha as categorias que você atende",
    licenseNum: "Número da Licença",
    licenseExpiry: "Validade da Licença",
    
    planSelect: "Selecione seu Plano",
    founderOffer: "OFERTA FUNDADOR",
    premiumPlan: "Plano Premium",
    lifetimeAccess: "Acesso Vitalício",
    benefitSite: "Site Pro + SEO",
    benefitPriority: "Destaque na Busca",
    benefitFees: "0% de Comissão",
    benefitSupport: "Suporte Dedicado",
    benefitBadge: "Selo Fundador",
    durationLabel: "Duração:",
    freeForever: "Grátis para Sempre",
    basicPlan: "Plano Básico",
    basicDesc: "Acesso padrão à plataforma",
    payoutDetails: "Dados de Recebimento",
    iban: "IBAN",
    accHolder: "Titular da Conta",
    paymentMethod: "Forma de Pagamento",
    expiryDate: "MM/AA",
    cvc: "CVC",
    cardHolder: "Nome no Cartão",
    websiteReady: "Site Pronto!",
    websiteDesc: "Seu site profissional está pronto.",
    visitSite: "Ver Site",
    generatedFor: "Gerado para",
    declaration: "Declaro que as informações estão corretas.",
    paymentValidation: "Necessário para validação. Não será cobrado hoje.",
    
    back: "Voltar",
    next: "Próximo",
    finish: "Finalizar",
    
    heroTitle: "Encontre os melhores <span class='text-emerald-500'>profissionais</span> em Luxemburgo",
    heroSubtitle: "Orçamentos em minutos para limpeza, obras, mudanças e mais.",
    searchPlaceholder: "O que você precisa?",
    trustSecure: "Pros Verificados",
    trustStars: "Bem Avaliados",
    trustFast: "Rápido",
    popularCategories: "Profissionais Populares", // UPDATED
    viewAllServices: "Ver todos os serviços", // NEW
    allServicesTitle: "Encontre o especialista ideal", // NEW
    exploreServices: "Explore nossos serviços",
    results: "Resultados",
    noServices: "Nenhum serviço para",
    clearSearch: "Limpar busca",
    proCTA: "Você é Profissional?",
    proCTADesc: "Junte-se à rede e cresça seu negócio.",
    proCTABtn: "Cadastrar como Pro",
    noCompany: "Sem Empresa?",
    openCompanyHelpBtn: "Nós ajudamos",
    openCompanyBtn: "Abrir Empresa",
    
    // SECTORS
    sectorHome: "Casa & Construção",
    sectorAuto: "Auto & Transporte",
    sectorTech: "Tech & Digital",
    sectorBusiness: "Empresas & Jurídico",
    sectorEvents: "Eventos & Festas",
    sectorLifestyle: "Estilo de Vida",
    sectorEducation: "Educação & Música",

    whatNeed: "O que você precisa?",
    describeProblem: "Descreva seu pedido",
    whereWhen: "Onde e Quando?",
    defineLocation: "Local e horário",
    photosOptional: "Fotos (Opcional)",
    helpPro: "Ajude os pros a entender",
    stepXofY: "Passo {x} de {y}",
    titleLabel: "Título",
    titlePlaceholder: "ex: Torneira vazando",
    detailsLabel: "Detalhes",
    detailsPlaceholder: "Descreva o problema...",
    addressPlaceholder: "Digite o endereço",
    whenLabel: "Para quando?",
    urgencyAsap: "O quanto antes",
    urgencyThisWeek: "Esta semana",
    urgencyPlanning: "Planejamento",
    budgetLabel: "Orçamento",
    budgetPlaceholder: "Orçamento estimado",
    budgetHelp: "Ajuda a receber propostas melhores",
    addPhoto: "Adicionar Foto",
    photoTip: "Fotos ajudam a ter orçamentos precisos",
    requestQuotes: "Pedir Orçamentos",
    saveChanges: "Salvar Alterações",
    myRequests: "Meus Pedidos",
    manageRequests: "Gerencie seus pedidos de serviço",
    createFirstRequest: "Criar Pedido",
    noActiveRequests: "Nenhum pedido ativo",
    goToMarket: "Ir ao Mercado",
    editRequest: "Editar",
    deleteRequest: "Excluir",
    
    historyTab: "Histórico",
    noRequestsDesc: "Sem histórico disponível",
    financialPerformance: "Painel Financeiro",
    filterToday: "Hoje",
    filterWeek: "Últ. 7 Dias",
    filterMonth: "Últ. 30 Dias",
    filterYear: "Este Ano",
    totalEarnings: "Faturamento Bruto",
    jobsCompleted: "Jobs",
    breakdown: "Transações",
    noJobsPeriod: "Sem transações neste período",
    messagesTab: "Mensagens",
    radar: "Radar",
    nearby: "Próximos",
    offerLabel: "Oferta",
    yourOffer: "Sua Oferta",
    acceptAndChat: "Aceitar e Conversar",
    availBalance: "Saldo Disponível",
    pendingBalance: "A Receber",
    vatEstimate: "Estimativa IVA (17%)",
    exportReport: "Exportar Relatório",
    downloadPdf: "Baixar PDF",
    invoiceNo: "Fatura N°",
    client: "Cliente",
    service: "Serviço",
    amountHT: "Valor (HT)",
    amountTTC: "Total (TTC)",
    revenueTrend: "Tendência de Receita",
    averageValue: "Ticket Médio",
    
    // NEW FINANCIAL KEYS
    addExternalService: "Adicionar Serviço Externo",
    externalServiceDef: "Serviço Externo",
    selectCategory: "Selecionar Categoria",
    addTransaction: "Adicionar Transação",
    methodCash: "Dinheiro",
    methodCard: "Cartão",
    methodTransfer: "Transferência",
    filterAll: "Todos",
    methodColumn: "Método",
    actionColumn: "Ação",
    provisionTax: "Provisão para impostos futuros",
    monthlyAgg: "Agregação Mensal",
    dailyBreak: "Detalhamento Diário",
    expandRange: "Tente selecionar um período maior.",
    upgradeTitle: "Mudar para Pro",
    upgradeText: "Desbloqueie o painel financeiro completo.",

    serviceAgreed: "Serviço acordado por",
    chatStarted: "Chat iniciado.",
    msgOnWay: "Estou a caminho.",
    msgArrived: "Cheguei ao local.",
    msgStarted: "Serviço iniciado.",
    msgPriceUpdate: "Preço atualizado para",
    proposalUpdate: "Atualização de Proposta",
    offerAccepted: "Oferta Aceita",
    offerDeclined: "Oferta Recusada",
    acceptOffer: "Aceitar Oferta",
    receiptTitle: "Recibo",
    startTime: "Início",
    endTime: "Fim",
    duration: "Duração",
    total: "Total",
    actionOnWay: "A Caminho",
    actionArrived: "Cheguei",
    actionStart: "Iniciar",
    actionFinish: "Finalizar",
    serviceCompleted: "Serviço Concluído",
    experienceQuestion: "Como foi sua experiência com",
    writeReview: "Escreva uma avaliação...",
    submitReview: "Enviar Avaliação",
    finishJob: "Gerar Fatura & Finalizar",
    onlineNow: "Online",
    typeMessage: "Digite uma mensagem...",
    leaveNegotiation: "Sair da Negociação?",
    leaveNegotiationDesc: "Você tem uma negociação ativa.",
    returnToMarket: "Voltar ao Mercado",
    stayHere: "Ficar Aqui",
    updateOffer: "Atualizar Oferta",
    newPrice: "Novo Preço",
    reasonChange: "Motivo da alteração",
    sendUpdate: "Enviar",
    confirmChange: "Confirmar Mudança",
    confirmChangeDesc: "Você aceita o preço de",
    confirmChangeSuffix: "?",
    yesConfirm: "Sim, Confirmar",
    cancel: "Cancelar",
    confirmWorkDone: "O serviço foi feito?",
    confirmWorkDoneDesc: "O Pro marcou como terminado. Confirme por favor.",
    yesFinished: "Sim, Finalizado",
    noNotYet: "Não, Ainda Não",
    confirmPayment: "Recebeu o pagamento?",
    confirmPaymentDesc: "Cliente confirmou. Você recebeu o valor?",
    yesReceived: "Sim, Recebido",
    chatArchived: "Chat Arquivado",
    reopenChat: "Reabrir Chat",
    waitingClient: "Aguardando Cliente...",
    waitingPayment: "Aguardando Pagamento...",
    liveFeed: "Feed ao Vivo",
    opportunities: "Oportunidades",
    liveMarket: "Mercado ao Vivo",
    jobClosed: "Trabalho Encerrado e Arquivado.",
    invoiceGen: "Fatura Gerada. Aguardando confirmação do cliente.",
    chatReopened: "Chat Reaberto.",
    statusConfirmed: "Serviço Confirmado",
    subConfirmed: "Pro aceitou o pedido",
    statusEnRoute: "A Caminho",
    subEnRoute: "Pro está se deslocando",
    statusArrived: "Chegou",
    subArrived: "Pro está no local",
    statusInProgress: "Em Andamento",
    subInProgress: "Serviço sendo executado",
    statusCompleted: "Concluído",
    subCompleted: "Serviço finalizado",
    
    personalInfo: "Dados Pessoais",
    companyData: "Dados da Empresa",
    addressLogistics: "Endereço e Logística",
    security: "Segurança",
    logisticsNote: "Logística",
    luxNoteDesc: "Info logística Luxemburgo",
    companyDesc: "Gerenciar detalhes da empresa",
    cantEditHelp: "Alguns campos são somente leitura",
    legalForm: "Forma Legal",
    govAuth: "Aut. Governamental",
    banking: "Bancário",
    manageIdentity: "Gerenciar Identidade",
    languages: "Idiomas",
    smartAddress: "Endereço Inteligente",
    connectPortfolio: "Conectar Instagram",
    connectPortfolioDesc: "Mostre seu trabalho direto do Instagram",
    connecting: "Conectando...",
    connectBtn: "Conectar",
    autoSync: "Sinc. Auto",
    instaConnected: "Instagram Conectado",
    itemsSynced: "itens sincronizados",
    disconnect: "Desconectar",
    noCaption: "Sem legenda",
    postedOn: "Postado em",
    wantService: "Quero este serviço",
    rating: "Avaliação",
    jobs: "Jobs",
    xp: "XP",
    speaks: "Fala",
    serviceLocation: "Local do Serviço",
    openMaps: "Abrir Mapa",
    bio: "Bio",
    serviceTimeline: "Linha do Tempo",
    hireNow: "Contratar",
    viewInstaBtn: "Ver Portfólio",
    recording: "Gravando",
    clientRole: "Cliente",
    reliableClient: "Confiável",
    requestsMade: "Pedidos",
    paymentRate: "Pagamentos",
    subscription: "Assinatura e Faturamento",
    currentPlan: "Plano Atual",
    paymentCard: "Cartão de Pagamento",
    changeCard: "Alterar Cartão",
    upgradePro: "Mude para o PRO",
    upgradeDesc: "Automatize sua contabilidade com faturas luxemburguesas compatíveis.",
    invBillTo: "Faturar Para",
    invDate: "Data da Fatura",
    invDue: "Vencimento",
    invDesc: "Descrição",
    invQty: "Qtd",
    invRate: "Taxa",
    invTotal: "Total",
    invSubtotal: "Subtotal (HT)",
    invVatAmt: "Valor IVA",
    invTotalDue: "Total a Pagar (TTC)",
    invFooter: "Pagamento em até 14 dias.",
    businessHours: "Horário de Funcionamento",
    openingTime: "Abertura",
    closingTime: "Fechamento",
    workingDays: "Dias de Funcionamento",
    addToFavorites: "Favoritar",
    removeFromFavorites: "Remover Favorito",
    blockContact: "Bloquear Empresa",
    unblockContact: "Desbloquear",
    blockedUsers: "Bloqueados",
    noBlockedUsers: "Nenhum usuário bloqueado.",
    favoritesTab: "Favoritos",
    noFavorites: "Nenhum favorito ainda.",
    contactInfo: "Dados do Contato",
    onlinePresence: "Social e Web",
    startDate: "De",
    endDate: "Até",
    customRange: "Intervalo Personalizado",
    roleLabel: "Função:",
    quickAccess: "Acesso Rápido (Demo)",
    orLoginManual: "Ou login manual",
    licenseInfo: "Licença emitida pelo Ministério da Economia.",
    uploadPdfLabel: "Carregar PDF / Foto",
    attached: "Documento Anexado",
    instaPortfolio: "Portfólio Instagram",
    summaryServices: "Serviços",
    summaryPlan: "Plano",
    summaryIban: "IBAN",
    activePlan: "(Ativo)",
    closedDay: "Fechado",
    
    chatSettings: "Config. de Chat",
    smartReply: "Resposta Inteligente",
    smartReplyDesc: "Resposta automática quando você estiver dirigindo ou ocupado.",
    activationTime: "Ativar se não responder em:",
    immediate: "Imediato",
    mins5: "5 Minutos",
    mins15: "15 Minutos",
    botPersonality: "Personalidade do Bot",
    agilityMode: "Agilidade (Foco em Velocidade)",
    agilityDesc: "Informa que você está dirigindo e responderá em breve.",
    dataMode: "Coleta de Dados (Recomendado)",
    dataDesc: "Pede fotos e detalhes para agilizar o orçamento.",
    customMode: "Mensagem Personalizada",
    customDesc: "Escreva sua própria mensagem de boas-vindas.",
    botMsgFooter: "Resposta automática - Profissional notificado.",
    enableAutoReply: "Ativar respostas automáticas",
    preview: "Pré-visualização",
    yourMessage: "Sua Mensagem",
    botMessageAgility: "Olá! Sou o assistente virtual. O profissional está dirigindo ou em serviço no momento. Ele já recebeu seu pedido e responderá pessoalmente assim que possível!",
    botMessageData: "Obrigado por nos escolher! Estou finalizando um atendimento. Para agilizar, poderia me enviar fotos do local ou descrever o problema com mais detalhes aqui? Já já eu respondo.",
    botMessageCustomDefault: "Bem-vindo! Estarei com você em breve.",
    
    financialErp: "Financeiro (ERP)",
    scanningJobs: "Procurando trabalhos...",
    upgradeNow: "Fazer Upgrade Agora",
    upgradeBtn: "Upgrade",
    stepIndicator: "Passo {step} de {total}",
    licenseUploaded: "LICENCA_ENVIADA.PDF",
    
    tagPunctual: "Pontual",
    tagClean: "Limpeza",
    tagPro: "Profissional",
    tagFriendly: "Simpático",
    tagFair: "Preço Justo",
};

// --- GERMAN ---
const deTranslations: typeof enTranslations = {
    ...enTranslations,
    signIn: "Anmelden",
    welcomeSubtitle: "Willkommen zurück bei ServiceBid",
    imClient: "Ich bin Kunde",
    imPro: "Ich bin Profi",
    myWebsite: "Meine Webseite",
    siteStatus: "Seitenstatus",
    online: "ONLINE",
    offline: "OFFLINE",
    copyLink: "Link kopieren",
    shareWhatsapp: "Auf WhatsApp teilen",
    appearance: "Aussehen",
    selectTheme: "Thema wählen",
    accentColor: "Akzentfarbe",
    previewSite: "VORSCHAU MEINER SEITE 👁️",
    siteInfo: "Wussten Sie schon?",
    siteInfoDesc: "Ihr Seiteninhalt (Fotos, Bewertungen, Bio) wird automatisch von Ihrem Profil synchronisiert.",
    themeModern: "Modern",
    themeClassic: "Klassisch",
    themeBold: "Fett",
    themeMinimal: "Minimalistisch",
    visitExternal: "Öffnen",
    linkCopied: "Link kopiert!",
    loginWithEmail: "E-Mail",
    loginWithPhone: "Handy",
    email: "E-Mail",
    phoneLabel: "Handynummer",
    password: "Passwort",
    forgotPassword: "Passwort vergessen?",
    dontHaveAccount: "Kein Konto?",
    signUp: "Registrieren",
    loggedAs: "Angemeldet als",
    dashboard: "Dashboard",
    profile: "Profil",
    logout: "Abmelden",
    
    personalDetails: "Persönliche Daten",
    businessDetails: "Firmendaten",
    servicesAndScope: "Dienstleistungen",
    licenseDetails: "Lizenzdetails",
    financialPlan: "Finanzplan",
    reviewDetails: "Überprüfung",
    fullName: "Vollständiger Name",
    cnsNumber: "CNS Nummer",
    street: "Straße",
    houseNumber: "Nummer",
    postalCode: "Postleitzahl",
    locality: "Ort",
    idUpload: "Ausweis hochladen",
    independant: "Selbstständig",
    societe: "Gesellschaft (S.à r.l.)",
    companyName: "Firmenname",
    tvaNumber: "MwSt-Nummer",
    rcsNumber: "RCS Nummer",
    selectServices: "Wählen Sie Ihre Dienste",
    selectServicesDesc: "Wählen Sie die Kategorien, in denen Sie arbeiten",
    licenseNum: "Lizenznummer",
    licenseExpiry: "Lizenzablauf",
    
    planSelect: "Wählen Sie Ihren Plan",
    founderOffer: "GRÜNDERANGEBOT",
    premiumPlan: "Premium Plan",
    lifetimeAccess: "Lebenslanger Zugang",
    benefitSite: "Pro Website + SEO",
    benefitPriority: "Suchpriorität",
    benefitFees: "0% Provision",
    benefitSupport: "Dedizierter Support",
    benefitBadge: "Gründerabzeichen",
    durationLabel: "Dauer:",
    freeForever: "Für immer kostenlos",
    basicPlan: "Basis Plan",
    basicDesc: "Standardzugang zur Plattform",
    payoutDetails: "Auszahlungsdetails",
    iban: "IBAN",
    accHolder: "Kontoinhaber",
    paymentMethod: "Zahlungsmethode",
    expiryDate: "MM/JJ",
    cvc: "CVC",
    cardHolder: "Karteninhaber",
    websiteReady: "Webseite Bereit!",
    websiteDesc: "Ihre professionelle Seite ist fertig.",
    visitSite: "Seite besuchen",
    generatedFor: "Erstellt für",
    declaration: "Ich erkläre, dass die Angaben korrekt sind.",
    paymentValidation: "Zur Überprüfung erforderlich. Heute keine Abbuchung.",
    
    back: "Zurück",
    next: "Weiter",
    finish: "Fertigstellen",
    
    heroTitle: "Finden Sie die besten <span class='text-emerald-500'>Profis</span> in Luxemburg",
    heroSubtitle: "Angebote in Minuten für Reinigung, Renovierung, Umzug und mehr.",
    searchPlaceholder: "Was benötigen Sie?",
    trustSecure: "Geprüfte Profis",
    trustStars: "Top Bewertet",
    trustFast: "Schnelle Angebote",
    popularCategories: "Beliebte Profis", // UPDATED
    viewAllServices: "Alle Dienste anzeigen", // NEW
    allServicesTitle: "Finden Sie den idealen Spezialisten", // NEW
    exploreServices: "Dienste erkunden",
    results: "Ergebnisse",
    noServices: "Keine Dienste gefunden für",
    clearSearch: "Suche löschen",
    proCTA: "Sind Sie ein Profi?",
    proCTADesc: "Treten Sie dem Netzwerk bei und erweitern Sie Ihr Geschäft.",
    proCTABtn: "Als Profi registrieren",
    noCompany: "Keine Firma?",
    openCompanyHelpBtn: "Wir helfen beim Start",
    openCompanyBtn: "Firma gründen",
    
    // SECTORS
    sectorHome: "Haus & Bau",
    sectorAuto: "Auto & Transport",
    sectorTech: "Technologie & Digital",
    sectorBusiness: "Wirtschaft & Recht",
    sectorEvents: "Events & Party",
    sectorLifestyle: "Lifestyle & Pflege",
    sectorEducation: "Bildung & Musik",

    whatNeed: "Was benötigen Sie?",
    describeProblem: "Beschreiben Sie Ihre Anfrage",
    whereWhen: "Wo & Wann?",
    defineLocation: "Ort und Zeit",
    photosOptional: "Fotos (Optional)",
    helpPro: "Helfen Sie den Profis zu verstehen",
    stepXofY: "Schritt {x} von {y}",
    titleLabel: "Titel",
    titlePlaceholder: "z.B. Tropfender Wasserhahn",
    detailsLabel: "Details",
    detailsPlaceholder: "Beschreiben Sie das Problem...",
    addressPlaceholder: "Adresse eingeben",
    whenLabel: "Für wann?",
    urgencyAsap: "So schnell wie möglich",
    urgencyThisWeek: "Diese Woche",
    urgencyPlanning: "Planung",
    budgetLabel: "Budget",
    budgetPlaceholder: "Geschätztes Budget",
    budgetHelp: "Hilft, bessere Angebote zu erhalten",
    addPhoto: "Foto hinzufügen",
    photoTip: "Fotos helfen, genaue Angebote zu erhalten",
    requestQuotes: "Angebote anfordern",
    saveChanges: "Änderungen speichern",
    myRequests: "Meine Anfragen",
    manageRequests: "Verwalten Sie Ihre Serviceanfragen",
    createFirstRequest: "Anfrage erstellen",
    noActiveRequests: "Keine aktiven Anfragen",
    goToMarket: "Zum Markt",
    editRequest: "Bearbeiten",
    deleteRequest: "Löschen",
    
    historyTab: "Verlauf",
    noRequestsDesc: "Kein Verlauf verfügbar",
    financialPerformance: "Finanz-Dashboard",
    filterToday: "Heute",
    filterWeek: "Letzte 7 Tage",
    filterMonth: "Letzte 30 Tage",
    filterYear: "Dieses Jahr",
    totalEarnings: "Bruttoumsatz",
    jobsCompleted: "Jobs",
    breakdown: "Transaktionen",
    noJobsPeriod: "Keine Transaktionen in diesem Zeitraum",
    messagesTab: "Nachrichten",
    radar: "Radar",
    nearby: "In der Nähe",
    offerLabel: "Angebot",
    yourOffer: "Ihr Angebot",
    acceptAndChat: "Annehmen & Chatten",
    availBalance: "Verfügbares Guthaben",
    pendingBalance: "Ausstehend",
    vatEstimate: "MwSt Schätzung (17%)",
    exportReport: "Steuerbericht exportieren",
    downloadPdf: "PDF herunterladen",
    invoiceNo: "Rechnung Nr.",
    client: "Kunde",
    service: "Dienstleistung",
    amountHT: "Betrag (Netto)",
    amountTTC: "Gesamt (Brutto)",
    revenueTrend: "Umsatztrend",
    averageValue: "Durchschn. Ticket",
    
    // NEW FINANCIAL KEYS
    addExternalService: "Externen Service hinzufügen",
    externalServiceDef: "Externer Service",
    selectCategory: "Kategorie wählen",
    addTransaction: "Transaktion hinzufügen",
    methodCash: "Bar",
    methodCard: "Karte",
    methodTransfer: "Überweisung",
    filterAll: "Alle",
    methodColumn: "Methode",
    actionColumn: "Aktion",
    provisionTax: "Rückstellung für zukünftige Steuern",
    monthlyAgg: "Monatliche Zusammenfassung",
    dailyBreak: "Tägliche Aufschlüsselung",
    expandRange: "Versuchen Sie einen größeren Datumsbereich.",
    upgradeTitle: "Upgrade auf Pro",
    upgradeText: "Schalten Sie das volle Finanz-Dashboard frei.",

    serviceAgreed: "Service vereinbart für",
    chatStarted: "Chat gestartet.",
    msgOnWay: "Ich bin auf dem Weg.",
    msgArrived: "Ich bin angekommen.",
    msgStarted: "Service gestartet.",
    msgPriceUpdate: "Preis aktualisiert auf",
    proposalUpdate: "Angebotsaktualisierung",
    offerAccepted: "Angebot angenommen",
    offerDeclined: "Angebot abgelehnt",
    acceptOffer: "Angebot annehmen",
    receiptTitle: "Quittung",
    startTime: "Startzeit",
    endTime: "Endzeit",
    duration: "Dauer",
    total: "Gesamt",
    actionOnWay: "Auf dem Weg",
    actionArrived: "Angekommen",
    actionStart: "Starten",
    actionFinish: "Beenden",
    serviceCompleted: "Service abgeschlossen",
    experienceQuestion: "Wie war Ihre Erfahrung mit",
    writeReview: "Bewertung schreiben...",
    submitReview: "Bewertung abgeben",
    finishJob: "Rechnung erstellen & Beenden",
    onlineNow: "Online",
    typeMessage: "Nachricht eingeben...",
    leaveNegotiation: "Verhandlung verlassen?",
    leaveNegotiationDesc: "Sie haben eine aktive Verhandlung.",
    returnToMarket: "Zurück zum Markt",
    stayHere: "Hier bleiben",
    updateOffer: "Angebot aktualisieren",
    newPrice: "Neuer Preis",
    reasonChange: "Grund für Änderung",
    sendUpdate: "Senden",
    confirmChange: "Änderung bestätigen",
    confirmChangeDesc: "Akzeptieren Sie den Preis von",
    confirmChangeSuffix: "?",
    yesConfirm: "Ja, Bestätigen",
    cancel: "Abbrechen",
    confirmWorkDone: "Ist die Arbeit erledigt?",
    confirmWorkDoneDesc: "Der Profi hat den Job als erledigt markiert. Bitte bestätigen.",
    yesFinished: "Ja, Erledigt",
    noNotYet: "Nein, Noch nicht",
    confirmPayment: "Haben Sie die Zahlung erhalten?",
    confirmPaymentDesc: "Kunde hat bestätigt. Haben Sie den Betrag erhalten?",
    yesReceived: "Ja, Erhalten",
    chatArchived: "Chat archiviert",
    reopenChat: "Chat wieder öffnen",
    waitingClient: "Warten auf Kunde...",
    waitingPayment: "Warten auf Zahlung...",
    liveFeed: "Live Feed",
    opportunities: "Chancen",
    liveMarket: "Live Markt",
    jobClosed: "Job geschlossen & archiviert.",
    invoiceGen: "Rechnung erstellt. Warte auf Kundenbestätigung.",
    chatReopened: "Chat wiedereröffnet.",
    statusConfirmed: "Service Bestätigt",
    subConfirmed: "Profi hat die Anfrage angenommen",
    statusEnRoute: "Unterwegs",
    subEnRoute: "Profi reist zum Standort",
    statusArrived: "Angekommen",
    subArrived: "Profi ist vor Ort",
    statusInProgress: "In Arbeit",
    subInProgress: "Service wird durchgeführt",
    statusCompleted: "Abgeschlossen",
    subCompleted: "Service beendet",
    
    personalInfo: "Persönliche Daten",
    companyData: "Firmendaten",
    addressLogistics: "Adresse & Logistik",
    security: "Sicherheit",
    logisticsNote: "Logistik",
    luxNoteDesc: "Luxemburg Logistik Info",
    companyDesc: "Firmendetails verwalten",
    cantEditHelp: "Einige Felder sind schreibgeschützt",
    legalForm: "Rechtsform",
    govAuth: "Regierungsauthorisierung",
    banking: "Bankwesen",
    manageIdentity: "Identität verwalten",
    languages: "Sprachen",
    smartAddress: "Intelligente Adresse",
    connectPortfolio: "Instagram verbinden",
    connectPortfolioDesc: "Zeigen Sie Ihre Arbeit direkt von Instagram",
    connecting: "Verbinden...",
    connectBtn: "Verbinden",
    autoSync: "Auto Sync",
    instaConnected: "Instagram verbunden",
    itemsSynced: "Elemente synchronisiert",
    disconnect: "Trennen",
    noCaption: "Keine Bildunterschrift",
    postedOn: "Gepostet am",
    wantService: "Ich möchte diesen Service",
    rating: "Bewertung",
    jobs: "Jobs",
    xp: "XP",
    speaks: "Spricht",
    serviceLocation: "Serviceort",
    openMaps: "Karten öffnen",
    bio: "Bio",
    serviceTimeline: "Service-Zeitlinie",
    hireNow: "Beauftragen",
    viewInstaBtn: "Portfolio ansehen",
    recording: "Aufnahme",
    clientRole: "Kunde",
    reliableClient: "Zuverlässig",
    requestsMade: "Anfragen",
    paymentRate: "Zahlungsrate",
    subscription: "Abo & Abrechnung",
    currentPlan: "Aktueller Plan",
    paymentCard: "Zahlungskarte",
    changeCard: "Karte ändern",
    upgradePro: "Upgrade auf PRO",
    upgradeDesc: "Automatisieren Sie Ihre Buchhaltung mit konformen luxemburgischen Rechnungen.",
    invBillTo: "Rechnung an",
    invDate: "Rechnungsdatum",
    invDue: "Fälligkeit",
    invDesc: "Beschreibung",
    invQty: "Menge",
    invRate: "Satz",
    invTotal: "Gesamt",
    invSubtotal: "Zwischensumme (Netto)",
    invVatAmt: "MwSt Betrag",
    invTotalDue: "Gesamtbetrag (Brutto)",
    invFooter: "Zahlung fällig innerhalb von 14 Tagen.",
    businessHours: "Öffnungszeiten",
    openingTime: "Öffnung",
    closingTime: "Schließung",
    workingDays: "Arbeitstage",
    addToFavorites: "Zu Favoriten hinzufügen",
    removeFromFavorites: "Aus Favoriten entfernen",
    blockContact: "Firma blockieren",
    unblockContact: "Entblocken",
    blockedUsers: "Blockierte Nutzer",
    noBlockedUsers: "Keine blockierten Nutzer.",
    favoritesTab: "Favoriten",
    noFavorites: "Noch keine Favoriten.",
    contactInfo: "Kontaktinfo",
    onlinePresence: "Online & Sozial",
    startDate: "Von",
    endDate: "Bis",
    customRange: "Benutzerdefiniert",
    roleLabel: "Rolle:",
    quickAccess: "Schnellzugriff (Demo)",
    orLoginManual: "Oder manuell anmelden",
    licenseInfo: "Diese Lizenz wird vom Wirtschaftsministerium ausgestellt.",
    uploadPdfLabel: "PDF / Foto hochladen",
    attached: "Dokument angehängt",
    instaPortfolio: "Instagram Portfolio",
    summaryServices: "Dienste",
    summaryPlan: "Plan",
    summaryIban: "IBAN",
    activePlan: "(Aktiv)",
    closedDay: "Geschlossen",
    
    chatSettings: "Chat-Einstellungen",
    smartReply: "Intelligente Antwort",
    smartReplyDesc: "Automatische Antwort, wenn Sie beschäftigt sind oder fahren.",
    activationTime: "Aktivieren wenn keine Antwort in:",
    immediate: "Sofort",
    mins5: "5 Minuten",
    mins15: "15 Minuten",
    botPersonality: "Bot-Persönlichkeit",
    agilityMode: "Agilität (Fokus Geschwindigkeit)",
    agilityDesc: "Informiert, dass Sie fahren und bald antworten.",
    dataMode: "Datensammlung (Empfohlen)",
    dataDesc: "Fragt nach Fotos und Details, um das Angebot zu beschleunigen.",
    customMode: "Benutzerdefinierte Nachricht",
    customDesc: "Schreiben Sie Ihre eigene Begrüßungsnachricht.",
    botMsgFooter: "Automatische Antwort - Profi benachrichtigt.",
    enableAutoReply: "Automatische Antworten aktivieren",
    preview: "Vorschau",
    yourMessage: "Ihre Nachricht",
    botMessageAgility: "Hallo! Ich bin der virtuelle Assistent. Der Profi fährt oder arbeitet gerade. Er hat Ihre Anfrage erhalten und wird so schnell wie möglich persönlich antworten!",
    botMessageData: "Danke, dass Sie uns gewählt haben! Ich beende gerade einen Job. Um Zeit zu sparen, könnten Sie Fotos senden oder das Problem hier genauer beschreiben? Ich antworte in Kürze.",
    botMessageCustomDefault: "Willkommen! Ich bin gleich bei Ihnen.",
    
    financialErp: "Finanzen (ERP)",
    scanningJobs: "Suche nach Jobs...",
    upgradeNow: "Jetzt upgraden",
    upgradeBtn: "Upgrade",
    stepIndicator: "Schritt {step} von {total}",
    licenseUploaded: "LIZENZ_HOCHGELADEN.PDF",
    
    tagPunctual: "Pünktlich",
    tagClean: "Sauber",
    tagPro: "Professionell",
    tagFriendly: "Freundlich",
    tagFair: "Fairer Preis",
};

// --- LUXEMBOURGISH ---
const lbTranslations: typeof enTranslations = {
    ...enTranslations,
    signIn: "Aloggen",
    welcomeSubtitle: "Wëllkomm zréck bei ServiceBid",
    imClient: "Ech si Client",
    imPro: "Ech si Pro",
    myWebsite: "Meng Websäit",
    siteStatus: "Säitestatus",
    online: "ONLINE",
    offline: "OFFLINE",
    copyLink: "Link kopéieren",
    shareWhatsapp: "Op WhatsApp deelen",
    appearance: "Ausgesinn",
    selectTheme: "Thema wielen",
    accentColor: "Akzentfaarf",
    previewSite: "MENG SÄIT UKUCKEN 👁️",
    siteInfo: "Wosst Dir schonn?",
    siteInfoDesc: "Ären Inhalt (Fotoen, Bewäertungen, Bio) gëtt automatesch vun Ärem Profil synchroniséiert.",
    themeModern: "Modern",
    themeClassic: "Klassesch",
    themeBold: "Fet",
    themeMinimal: "Minimalistesch",
    visitExternal: "Opmaachen",
    linkCopied: "Link kopéiert!",
    loginWithEmail: "E-Mail",
    loginWithPhone: "Handy",
    email: "E-Mail",
    phoneLabel: "Handysnummer",
    password: "Passwuert",
    forgotPassword: "Passwuert vergiess?",
    dontHaveAccount: "Keen Kont?",
    signUp: "Umellen",
    loggedAs: "Ageloggt als",
    dashboard: "Dashboard",
    profile: "Profil",
    logout: "Ausloggen",
    
    personalDetails: "Perséinlech Detailer",
    businessDetails: "Firmendaten",
    servicesAndScope: "Servicer & Ëmfang",
    licenseDetails: "Lizenz Detailer",
    financialPlan: "Finanzplang",
    reviewDetails: "Iwwerpréiwung",
    fullName: "Ganzen Numm",
    cnsNumber: "CNS Nummer",
    street: "Strooss",
    houseNumber: "Nummer",
    postalCode: "Postleitzuel",
    locality: "Uertschaft",
    idUpload: "Ausweis eroplueden",
    independant: "Independant",
    societe: "Société (S.à r.l.)",
    companyName: "Firmennumm",
    tvaNumber: "TVA Nummer",
    rcsNumber: "RCS Nummer",
    selectServices: "Wielt Är Servicer",
    selectServicesDesc: "Wielt d'Kategorien an deenen Dir schafft",
    licenseNum: "Lizenznummer",
    licenseExpiry: "Lizenz Oflafdatum",
    
    planSelect: "Wielt Äre Plang",
    founderOffer: "GRËNNER OFFER",
    premiumPlan: "Premium Plang",
    lifetimeAccess: "Liewenslaangen Zougang",
    benefitSite: "Pro Websäit + SEO",
    benefitPriority: "Sich Prioritéit",
    benefitFees: "0% Kommissioun",
    benefitSupport: "Dedizéierten Support",
    benefitBadge: "Grënner Badge",
    durationLabel: "Dauer:",
    freeForever: "Gratis fir ëmmer",
    basicPlan: "Basis Plang",
    basicDesc: "Standard Zougang zur Plattform",
    payoutDetails: "Ausbezuelungsdetailer",
    iban: "IBAN",
    accHolder: "Konthalter",
    paymentMethod: "Bezuelmethod",
    expiryDate: "MM/JJ",
    cvc: "CVC",
    cardHolder: "Kaartenhalter",
    websiteReady: "Websäit Bereet!",
    websiteDesc: "Är professionell Säit ass fäerdeg.",
    visitSite: "Säit besichen",
    generatedFor: "Generéiert fir",
    declaration: "Ech erklären datt d'Informatioun richteg ass.",
    paymentValidation: "Néideg fir Verifikatioun. Haut keng Ofbuchung.",
    
    back: "Zréck",
    next: "Weider",
    finish: "Ofschléissen",
    
    heroTitle: "Fannt déi bescht <span class='text-emerald-500'>Profien</span> zu Lëtzebuerg",
    heroSubtitle: "Devis an e puer Minutten fir Botzen, Renovatioun, Plënneren a méi.",
    searchPlaceholder: "Wat braucht Dir?",
    trustSecure: "Verifizéiert Profien",
    trustStars: "Top Bewäert",
    trustFast: "Séier Devisen",
    popularCategories: "Beléifte Profien", // UPDATED
    viewAllServices: "All Servicer kucken", // NEW
    allServicesTitle: "Fannt den idealen Spezialist", // NEW
    exploreServices: "Entdeckt eis Servicer",
    results: "Resultater",
    noServices: "Keng Servicer fonnt fir",
    clearSearch: "Sich läschen",
    proCTA: "Sidd Dir e Profi?",
    proCTADesc: "Maacht mat beim Netzwierk a vergréissert Äert Geschäft.",
    proCTABtn: "Als Pro registréieren",
    noCompany: "Keng Firma?",
    openCompanyHelpBtn: "Mir hëllefen beim Start",
    openCompanyBtn: "Firma grënnen",
    
    // SECTORS
    sectorHome: "Heem & Bau",
    sectorAuto: "Auto & Transport",
    sectorTech: "Technologie & Digital",
    sectorBusiness: "Business & Gesetz",
    sectorEvents: "Events & Party",
    sectorLifestyle: "Lifestyle & Fleeg",
    sectorEducation: "Bildung & Musek",

    whatNeed: "Wat braucht Dir?",
    describeProblem: "Beschreift Är Ufro",
    whereWhen: "Wou & Wéini?",
    defineLocation: "Plaz an Zäit",
    photosOptional: "Fotoen (Optional)",
    helpPro: "Hëlleft de Profien ze verstoen",
    stepXofY: "Schrëtt {x} vun {y}",
    titleLabel: "Titel",
    titlePlaceholder: "z.B. Krunn dee leeft",
    detailsLabel: "Detailer",
    detailsPlaceholder: "Beschreift de Problem...",
    addressPlaceholder: "Adress aginn",
    whenLabel: "Fir wéini?",
    urgencyAsap: "Sou séier wéi méiglech",
    urgencyThisWeek: "Dës Woch",
    urgencyPlanning: "Planung",
    budgetLabel: "Budget",
    budgetPlaceholder: "Geschate Budget",
    budgetHelp: "Hëlleft besser Offeren ze kréien",
    addPhoto: "Foto dobäisetzen",
    photoTip: "Fotoen hëllefen präzis Devisen ze kréien",
    requestQuotes: "Devis ufroen",
    saveChanges: "Ännerungen späicheren",
    myRequests: "Meng Ufroen",
    manageRequests: "Gestioun vun Äre Service Ufroen",
    createFirstRequest: "Ufro erstellen",
    noActiveRequests: "Keng aktiv Ufroen",
    goToMarket: "Op de Maart",
    editRequest: "Änneren",
    deleteRequest: "Läschen",
    
    historyTab: "Verlaf",
    noRequestsDesc: "Keen Verlaf verfügbar",
    financialPerformance: "Finanz-Dashboard",
    filterToday: "Haut",
    filterWeek: "Lescht 7 Deeg",
    filterMonth: "Lescht 30 Deeg",
    filterYear: "Dëst Joer",
    totalEarnings: "Brutto Akommes",
    jobsCompleted: "Aarbechten",
    breakdown: "Transaktiounen",
    noJobsPeriod: "Keng Transaktiounen an dëser Period",
    messagesTab: "Messagen",
    radar: "Radar",
    nearby: "An der Géigend",
    offerLabel: "Offer",
    yourOffer: "Är Offer",
    acceptAndChat: "Unheelen & Chatten",
    availBalance: "Verfügbar",
    pendingBalance: "Ausstoend",
    vatEstimate: "TVA Schätzung (17%)",
    exportReport: "Steierbericht exportéieren",
    downloadPdf: "PDF eroflueden",
    invoiceNo: "Rechnung Nr.",
    client: "Client",
    service: "Service",
    amountHT: "Betrag (HT)",
    amountTTC: "Total (TTC)",
    revenueTrend: "Akommes Trend",
    averageValue: "Duerchschn. Ticket",
    
    // NEW FINANCIAL KEYS
    addExternalService: "Externe Service dobäisetzen",
    externalServiceDef: "Externe Service",
    selectCategory: "Kategorie wielen",
    addTransaction: "Transaktioun dobäisetzen",
    methodCash: "Boer",
    methodCard: "Kaart",
    methodTransfer: "Iwwerweisung",
    filterAll: "All",
    methodColumn: "Method",
    actionColumn: "Aktioun",
    provisionTax: "Provisioun fir zukünfteg Steieren",
    monthlyAgg: "Monatlech Zesummefaassung",
    dailyBreak: "Deeglechen Detail",
    expandRange: "Probéiert e méi groussen Datumsberäich.",
    upgradeTitle: "Upgrade op Pro",
    upgradeText: "Schalt de kompletten Finanz-Dashboard fräi.",

    serviceAgreed: "Service ausgemaach fir",
    chatStarted: "Chat gestart.",
    msgOnWay: "Ech sinn um Wee.",
    msgArrived: "Ech sinn ukomm.",
    msgStarted: "Service gestart.",
    msgPriceUpdate: "Präis aktualiséiert op",
    proposalUpdate: "Offer Aktualiséierung",
    offerAccepted: "Offer ugeholl",
    offerDeclined: "Offer ofgeleent",
    acceptOffer: "Offer unheelen",
    receiptTitle: "Reçu",
    startTime: "Startzäit",
    endTime: "Endzäit",
    duration: "Dauer",
    total: "Total",
    actionOnWay: "Um Wee",
    actionArrived: "Ukomm",
    actionStart: "Starten",
    actionFinish: "Ofschléissen",
    serviceCompleted: "Service ofgeschloss",
    experienceQuestion: "Wéi war Är Erfahrung mat",
    writeReview: "Bewäertung schreiwen...",
    submitReview: "Bewäertung ofginn",
    finishJob: "Rechnung generéieren & Ofschléissen",
    onlineNow: "Online",
    typeMessage: "Message schreiwen...",
    leaveNegotiation: "Verhandlung verloossen?",
    leaveNegotiationDesc: "Dir hutt eng aktiv Verhandlung.",
    returnToMarket: "Zréck op de Maart",
    stayHere: "Hei bleiwen",
    updateOffer: "Offer aktualiséieren",
    newPrice: "Neie Präis",
    reasonChange: "Grond fir Ännerung",
    sendUpdate: "Schécken",
    confirmChange: "Ännerung bestätegen",
    confirmChangeDesc: "Akzeptéiert Dir de Präis vun",
    confirmChangeSuffix: "?",
    yesConfirm: "Jo, Bestätegen",
    cancel: "Ofbriechen",
    confirmWorkDone: "Ass d'Aarbecht fäerdeg?",
    confirmWorkDoneDesc: "De Pro huet d'Aarbecht als fäerdeg markéiert. Bestätegt w.e.g.",
    yesFinished: "Jo, Fäerdeg",
    noNotYet: "Nee, Nach net",
    confirmPayment: "Hutt Dir d'Bezuelung kritt?",
    confirmPaymentDesc: "Client huet bestätegt. Hutt Dir de Betrag kritt?",
    yesReceived: "Jo, Kritt",
    chatArchived: "Chat archivéiert",
    reopenChat: "Chat nees opmaachen",
    waitingClient: "Warden op Client...",
    waitingPayment: "Warden op Bezuelung...",
    liveFeed: "Live Feed",
    opportunities: "Méiglechkeeten",
    liveMarket: "Live Maart",
    jobClosed: "Aarbecht zou & archivéiert.",
    invoiceGen: "Rechnung generéiert. Warden op Client Bestätegung.",
    chatReopened: "Chat nees opgemaach.",
    statusConfirmed: "Service Bestätegt",
    subConfirmed: "Pro huet d'Ufro ugeholl",
    statusEnRoute: "Um Wee",
    subEnRoute: "Pro reest op d'Plaz",
    statusArrived: "Ukomm",
    subArrived: "Pro ass op der Plaz",
    statusInProgress: "Am Gaang",
    subInProgress: "Service gëtt ausgefouert",
    statusCompleted: "Ofgeschloss",
    subCompleted: "Service fäerdeg",
    
    personalInfo: "Perséinlech Info",
    companyData: "Firmendaten",
    addressLogistics: "Adress & Logistik",
    security: "Sécherheet",
    logisticsNote: "Logistik",
    luxNoteDesc: "Lëtzebuerg Logistik Info",
    companyDesc: "Firmendetailer verwalten",
    cantEditHelp: "E puer Felder sinn nëmme liesbar",
    legalForm: "Rechtsform",
    govAuth: "Regierungsautorisatioun",
    banking: "Bankwesen",
    manageIdentity: "Identitéit verwalten",
    languages: "Sproochen",
    smartAddress: "Intelligent Adress",
    connectPortfolio: "Instagram verbannen",
    connectPortfolioDesc: "Weist Är Aarbecht direkt vun Instagram",
    connecting: "Verbannen...",
    connectBtn: "Verbannen",
    autoSync: "Auto Sync",
    instaConnected: "Instagram Verbonnen",
    itemsSynced: "Elementer synchroniséiert",
    disconnect: "Trennen",
    noCaption: "Keng Ënnerschrëft",
    postedOn: "Gepost um",
    wantService: "Ech wëll dëse Service",
    rating: "Bewäertung",
    jobs: "Aarbechten",
    xp: "XP",
    speaks: "Schwätzt",
    serviceLocation: "Service Plaz",
    openMaps: "Kaarten opmaachen",
    bio: "Bio",
    serviceTimeline: "Service Zäitlinn",
    hireNow: "Astellen",
    viewInstaBtn: "Portfolio uweisen",
    recording: "Opnam",
    clientRole: "Client",
    reliableClient: "Zouverlässeg",
    requestsMade: "Ufroen",
    paymentRate: "Bezuelungsquote",
    subscription: "Abo & Rechnung",
    currentPlan: "Aktuelle Plang",
    paymentCard: "Bezuelkaart",
    changeCard: "Kaart änneren",
    upgradePro: "Upgrade op PRO",
    upgradeDesc: "Automatiséiert Är Comptabilitéit mat konforme Lëtzebuerger Rechnungen.",
    invBillTo: "Rechnung un",
    invDate: "Rechnungsdatum",
    invDue: "Fällegkeet",
    invDesc: "Beschreiwung",
    invQty: "Quantitéit",
    invRate: "Taux",
    invTotal: "Total",
    invSubtotal: "Tëschenzomm (HT)",
    invVatAmt: "TVA Betrag",
    invTotalDue: "Total ze bezuelen (TTC)",
    invFooter: "Bezuelung fälleg bannent 14 Deeg.",
    businessHours: "Öffnungszäiten",
    openingTime: "Op",
    closingTime: "Zou",
    workingDays: "Aarbechtsdeeg",
    addToFavorites: "Zu Favoritten dobäisetzen",
    removeFromFavorites: "Vu Favoritten ewechhuelen",
    blockContact: "Firma blockéieren",
    unblockContact: "Deblockéieren",
    blockedUsers: "Blockéiert Benotzer",
    noBlockedUsers: "Keng blockéiert Benotzer.",
    favoritesTab: "Favoritten",
    noFavorites: "Nach keng Favoritten.",
    contactInfo: "Kontakt Info",
    onlinePresence: "Online & Sozial",
    startDate: "Vun",
    endDate: "Bis",
    customRange: "Benotzerdefinéiert",
    roleLabel: "Roll:",
    quickAccess: "Schnellzougang (Demo)",
    orLoginManual: "Oder manuell aloggen",
    licenseInfo: "Dës Lizenz gëtt vum Wirtschaftsministère ausgestallt.",
    uploadPdfLabel: "PDF / Foto eroplueden",
    attached: "Dokument ugehaang",
    instaPortfolio: "Instagram Portfolio",
    summaryServices: "Servicer",
    summaryPlan: "Plang",
    summaryIban: "IBAN",
    activePlan: "(Aktiv)",
    closedDay: "Zou",
    
    chatSettings: "Chat Astellungen",
    smartReply: "Intelligent Äntwert",
    smartReplyDesc: "Automatesch Äntwert wann Dir beschäftegt sidd oder fuert.",
    activationTime: "Aktivéieren wann keng Äntwert an:",
    immediate: "Direkt",
    mins5: "5 Minutten",
    mins15: "15 Minutten",
    botPersonality: "Bot Perséinlechkeet",
    agilityMode: "Agilitéit (Focus Geschwindegkeet)",
    agilityDesc: "Informéiert datt Dir fuert a geschwënn äntwert.",
    dataMode: "Datesammlung (Recommandéiert)",
    dataDesc: "Frot no Fotoen an Detailer fir den Devis ze beschleunegen.",
    customMode: "Benotzerdefinéiert Message",
    customDesc: "Schreift Ären eegene Begréissungsmessage.",
    botMsgFooter: "Automatesch Äntwert - Pro informéiert.",
    enableAutoReply: "Automatesch Äntwerten aktivéieren",
    preview: "Virschau",
    yourMessage: "Äre Message",
    botMessageAgility: "Moien! Ech sinn de virtuellen Assistent. De Profi fiert oder schafft momentan. Hien huet Är Ufro kritt an äntwert sou séier wéi méiglech perséinlech!",
    botMessageData: "Merci datt Dir eis gewielt hutt! Ech maachen grad eng Aarbecht fäerdeg. Fir Zäit ze spueren, kéint Dir Fotoen schécken oder de Problem hei méi genee beschreiwen? Ech äntweren gläich.",
    botMessageCustomDefault: "Wëllkomm! Ech si gläich bei Iech.",
    
    financialErp: "Finanzen (ERP)",
    scanningJobs: "Sich no Aarbechten...",
    upgradeNow: "Elo upgraden",
    upgradeBtn: "Upgrade",
    stepIndicator: "Schrëtt {step} vun {total}",
    licenseUploaded: "LIZENZ_EROPGELUEDEN.PDF",
    
    tagPunctual: "Pünktlech",
    tagClean: "Propper",
    tagPro: "Professionell",
    tagFriendly: "Frëndlech",
    tagFair: "Faire Präis",
};

const translations = {
  EN: enTranslations,
  PT: ptTranslations,
  FR: frTranslations,
  DE: deTranslations,
  LB: lbTranslations
};

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: typeof enTranslations;
  tCategory: (catId: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  // SET DEFAULT LANGUAGE TO FRENCH ('FR') AS REQUESTED
  const [language, setLanguage] = useState<Language>('FR');

  const t = translations[language];

  // Helper to translate categories since they are dynamic IDs
  const tCategory = (catId: string) => {
    return catId; 
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tCategory }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
